### ISSUE TITLE
Access to popover element

### ISSUE THREAD

**Issue by cpoyraz** [sandywalker/webui-popover#103]
Hi,
I Show firstly loading animation in popover and will update when ajax request is completed.
For this, how can I Access popover dom element in Show event function ?

**Comment by sandywalker** [comment]
I've added the this.$target parameter in trigger show,shown and hide,hidden event, now you can access the popover by second parameter of your event handler function.
For example
```javascript
$el.on('show',function(e,pop){
			console.log(pop);					
});
'''
