### ISSUE TITLE
Support for easy knockout custom binding

### ISSUE THREAD

**Issue by vladud** [sandywalker/webui-popover#105]
The problem with making a custom binding for the bootstrap popover (and this library as well) is that you can only apply bindings after the content is rendered (i.e. at 'shown' event trigger). 
Because of this, the position of the popover is off (being calculated for the "empty" content) and also the event handlers that were bound before the ko.cleanNode() was called are removed. (e.g. the click handle for the ".close" class added in `initTargetEvents()`)

A simple solution would be just to trigger an 'added' event right after the content is appended to the body. 
Adding `this.$element.trigger('added.' + pluginType);` between the `$target.appendTo(document.body);` and `this.initTargetEvents();` lines should work well enough.

Not sure if this is a needed "feature" for the library but there could be people that want to use it.

**Comment by sandywalker** [comment]
Sure, I've added this feature to the plugin! 
Thanks for your advice.
