### ISSUE TITLE
Auto placement - error

### ISSUE THREAD

**Issue by muzcoltman** [sandywalker/webui-popover#106]
Hi Sandy,

I found a litte problem, when choosing "auto-bottom" or "auto-left" as placement.
In your code, starting at line 557, you are checking the middle width part with the clientHeight variable.

See line 560 and 568:
pageX < clientHeight * 2 /3

Here you have to use clientWidth instead of clientHeight.

Thank you for developing this amazing plugin. Saved me a lot of hours so far ;-)

Steven Coltman

**Comment by sandywalker** [comment]
Oh, That's my fault. Thank you very much  for point out this error !
