### ISSUE TITLE
Popover not opening on click when content loaded from json file (Wenzhixin bootstrap-table)

### ISSUE THREAD

**Issue by Same0717** [sandywalker/webui-popover#108]
Sandy thanks for the great work!  I have been using your webui-popover and it is great.  

Recently I have been trying to use it along with Wenzhixin bootstrap-table for it's sort capabilities. When I load my content into the bootstap-table via a .json file nothing happen when I click the link that should open a popover.  Best I can tell everything loads correctly but the popover doesn't open when clicked.

Any suggestions ? 
Thanks

**Comment by sandywalker** [comment]
Hi, I've tried the Wenzhixin bootstrap-table work with webui-popover and found it just working,  I can't find the problem which you have. Here is my testing code:

```javascript
   $('#table').bootstrapTable({
  		    columns: [{
  		        field: 'id',
  		        title: 'Item ID'
  		    }, {
  		        field: 'name',
  		        title: 'Item Name'
  		    }, {
  		        field: 'price',
  		        title: 'Item Price'
  		    }],
  		    data: [{
  		        id: 1,
  		        name: '<a href="#" class="abc">Item 1</a>',
  		        price: '$1'
  		    }, {
  		        id: 2,
  		        name: 'Item 2',
  		        price: '$2'
  		    }]
  		});

  		$('.abc').webuiPopover({
  			title:'ddd',
  			content:'dxxxxx'
  		});

```

**Comment by Same0717** [comment]
Thank you for the reply.  I believe my problem stems from having the table populating from a .json file.

````
<!DOCTYPE html>
<html lang="en">
  <head>
    <link type="text/css" rel="stylesheet" href="/css/base_style.css"/>
	<link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/bootstrap-table.css" type="text/css" rel="stylesheet" >
  </head>
  <body>
  <div class="container-fluid">
  <div class="col-xs-12">
<div class="row">
	<div class="col-xs-12">
    <div role="tabpanel">
      <ul class="nav nav-tabs" role="tablist">
        <li><a href="#14-15" data-toggle="tab" role="tab">2014-2015</a></li>
        <li class="active"><a href="#15-16" data-toggle="tab" role="tab">2015-2016</a></li>
          </ul>
      <div id="tabContent1" class="tab-content">
        <div class="tab-pane fade" id="14-15">
           <table class="table standings table-striped table-bordered" data-toggle="table" data-url="#" data-sort-name="date" data-sort-order="asc">
          
  <thead>
        <tr>
        <th data-field="date" data-align="center" data-sortable="true" data-sorter="datesort">Date</th>
        <th data-field="time" data-align="center" data-sortable="true">Time</th>
        <th data-field="opponent" data-align="center" data-sortable="true">Opponent</th>
        <th data-field="location" data-align="center" data-sortable="true">Location</th>
        <th data-field="results" data-align="center" data-sortable="true">Results</th>
      </tr>
    </thead>
		</table>
        </div>
        <div class="tab-pane fade in active" id="15-16">
           <table class="table standings table-striped table-bordered" data-toggle="table" data-url="/15-16result2.json" data-sort-name="date" data-sort-order="asc">
          
  <thead>
        <tr>
        <th data-field="date" data-align="center" data-sortable="true" data-sorter="datesort">Date</th>
        <th data-field="time" data-align="center" data-sortable="true">Time</th>
        <th data-field="opponent" data-align="center" data-sortable="true">Opponent</th>
        <th data-field="location" data-align="center" data-sortable="true">Location</th>
        <th data-field="results" data-align="center" data-sortable="true">Results</th>
      </tr>
    </thead>
		</table>
        </div>
      </div>
    </div>
        </div>
    </div>
       </div></div>
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) --> 
	<script src="/js/jquery-1.11.2.min.js"></script>

	<!-- Include all compiled plugins (below), or include individual files as needed --> 
	<script src="/js/bootstrap.js"></script>
    <script src="/js/bootstrap-table.js"></script>

<script>
function datesort(a,b) {
 var x = new Date(a),
     y = new Date(b);
 return ((x < y) ? -1 : ((x > y) ?  1 : 0));
};
</script>
    
    <link rel="stylesheet" href="/jquery.webui-popover.css">
    <script src="/jquery.webui-popover.js"></script>
    
    <script>										
	 $('.abc').webuiPopover({
            title:'ddd',
            content:'dxxxxx'
        });
	</script>
    
  </body>
</html>
````

JSON
``` 
[
    {
        "date": "11/3/15",
        "time": "12:00 pm",
        "opponent": "Test 1",
		"location": "<a href=\"#\" class=\"abc\" tabindex=\"0\" role=\"button\" data-toggle=\"popover\" title=\"<center>Test 1<\/center>\" data-trigger=\"click\" data-placement=\"auto-bottom\">home<\/a>",
		"results": ""
    },
     {
        "date": "11/4/15",
        "time": "2:00pm",
        "opponent": "Test 2",
		"location": "Away",
		"results": ""
    },
	    {
        "date": "11/5/15",
        "time": "1:00 pm",
        "opponent": "Test 3",
		"location": "Home",
		"results": ""
    }
]
```

Everything looks fine on the resulting page but when you click what should be the popover nothing happens.
<img width="1153" alt="screen shot 2015-10-02 at 4 07 23 pm" src="https://cloud.githubusercontent.com/assets/11163199/10256510/b90ec3b4-691f-11e5-9f91-19f23175f3f9.png">

**Comment by Same0717** [comment]
Just checking back to see if you have had an opportunity to look at this issue again ?

**Comment by sandywalker** [comment]
Sorry for so long delay, I tried your code and found the reason. 
The problem is in your code,when  you inited the popover, but the data of the bootstrap-table was not loaded,so your jQuery selector $('.abc') will return empty array, of course the popover can't be initialised.

To fix the problem, I suggest you init the bootstrap-table by javascript code instead of using data attribute, so you can init the popover in onLoadSuccess of bootstrap-table.

Here is my code, I've tested it, the popover worked fine with bootstrap-table.
```html
<table  id="jsontable" class="table standings table-striped table-bordered"  data-url="/demo/table-data.json" data-sort-name="date" data-sort-order="asc">

  <thead>
        <tr>
        <th data-field="date" data-align="center" data-sortable="true" data-sorter="datesort">Date</th>
        <th data-field="time" data-align="center" data-sortable="true">Time</th>
        <th data-field="opponent" data-align="center" data-sortable="true">Opponent</th>
        <th data-field="location" data-align="center" data-sortable="true">Location</th>
        <th data-field="results" data-align="center" data-sortable="true">Results</th>
      </tr>
    </thead>
</table>
```

```javascript
$('#jsontable').bootstrapTable({
        onLoadSuccess:function(data){
            $('.abc').webuiPopover({
                  title:'ddd',
                  content:'dxxxxx'
            });
        }
      });
```

**Comment by Same0717** [comment]
Thank you for the help.  That solved my problem!  Incase anyone else looks at this for a similar issue... 

The above solution worked perfectly on the original page load but if a user used the sort arrows to reorder the table it was again not working. (returning an empty array) To fix this I made one minor change to the javascript code such that the popover works on both original page load and after sorts. I changed onLoadSuccess to onPostBody

```
$('#jsontable').bootstrapTable({
        onPostBody:function(data){
            $('.abc').webuiPopover({
                  title:'ddd',
                  content:'dxxxxx'
            });
        }
      });
```

**Comment by AdiFloDev** [comment]
Hi,
I'm re-opening the thread on this matter because I'm having the same problem as Same0717 which is that on column reorder or page change the popover doesn't work anymore. And the onPostBody solution doesn't work for me as it doesn't return the data array.

Does anyone got this right ?

Here is my code which works for me only on first table load. 

`onLoadSuccess:function(data){
		
		$.each(data, function (key, array) {
			var row_designation = array['designation'];
			var row_content = array['details'];
			
			$('.popover_inbox_' + array['id']).webuiPopover({ 
				
				title: row_designation,
				content: row_content,
				placement:'auto',
				container: document.body, // The container in which the popover will be added (i.e. The parent scrolling area)
			    width:'800',//can be set with  number
			    height:'350', //can be set with  number
			    trigger:'hover',
			    animation: 'fade', //pop with animation,values: pop,fade (only take effect in the browser which support css3 transition)
			    delay: {//show and hide delay time of the popover, works only when trigger is 'hover',the value can be number or object
			        show: null,
			        hide: 300
			    },
			    padding:true,
			    type:'html',
			});
		});
	}`
