### ISSUE TITLE
Close popover on touch screen devices

### ISSUE THREAD

**Issue by kcijezie** [sandywalker/webui-popover#109]
Nice plugin. But when using a touch screen device (e.g Ipad) the popovers open but if you touch outside them it does not close as one would expect.

**Comment by sandywalker** [comment]
Sorry,I've not tested mobile devices yet. 
I'm working on it,These works should be done earlier,but I'm too busy.

**Comment by gavinhewitt** [comment]
+1 
Would be awesome if this could be fixed on short notice. We use it in production and it is a real issue for users.

**Comment by sandywalker** [comment]
I'll fix this problem as soon as possible,and optimise it for mobile later.

**Comment by Edddy** [comment]
@kcijezie Have you tried touching on an *element* outside? I've notice that the popup don't close if you touch on an empty space (outside of <body>), but do on any element outside.

**Comment by sandywalker** [comment]
I've optimised the touch event on mobile devices, the plugin works ok on my iPhone, Android Phone.

**Comment by george-norris-salesforce** [comment]
This is still a problem

**Comment by q2apro** [comment]
Reported by my iPad users, still an open problem. Date 2019-08-15.
