### ISSUE TITLE
Replace hide() with remove() on close

### ISSUE THREAD

**Issue by faralimite** [sandywalker/webui-popover#112]
Hi,

Is there any way to replace this.$target.removeClass('in').hide(); with this.$target.removeClass('in').remove(); for hide function? or add an option for this?
There are some issues if you define more divs using the same id (I'm using dynamic content loading)

Regards,
Radu

**Comment by sandywalker** [comment]
I checked your proposal, but sorry, this may cause other problems. If you want to remove popover each time,I suggest you set trigger option to  'manual', and control event handling yourself, use destroyed method before show again.

**Comment by serenasara** [comment]
jQuery(_button).webuiPopover({
                content:jQuery("div#tableContent").html(),
                width:500,
                trigger:'click',
                title:'title ',
                multi:true,
                closeable:true,
                style:'',
                delay:300,
                padding:true,
                arrow:true,
                onHide:function(e){
                    jQuery(e).remove();
                }
            });
