### ISSUE TITLE
How to get the clicked element through which popover is shown inside init?

### ISSUE THREAD

**Issue by maytas3** [sandywalker/webui-popover#113]
I have 10 buttons on my page, each of them being inside a section say section1, section2, section3...so on. Now inside init I am doing a ajax call based on the section which is clicked. Inside callback I have hidden the popover. After ajax call gets over, I show the popover, I show popover in success of ajax. So how can I get the button (and thus its parent) inside init? 

$(this).data("trigger-element") gives me undefined.

**Comment by sandywalker** [comment]
The problem you described is little complex, maybe you can put some of your code and i will try to help you .
