### ISSUE TITLE
Issue with to much elements having popovers

### ISSUE THREAD

**Issue by Hexodus** [sandywalker/webui-popover#114]
I have a page with 400+ elements using popovers. It's slowing down drasticly when they show up one by one. Maybe 100 popovers in the dom tree may be ok but 400 totaly kill the performance. Is it somehow possible to habe only one popover at the time or delete other instances other then the current?

**Comment by sandywalker** [comment]
400+?  I've tried 100 when i wrote this plugin and i thought that is enough, the fact is i'm wrong :) Have you turned the multi option to false?

**Comment by Hexodus** [comment]
Thanks for answering. Yes, I have a literature page and currently there is a plenty selpublisher books and ebooks out there so 400+ books have to be listed every month. 

Of course I tried the multiple: false first but it works an other way then I thought. I shows only one popover but it doesen't erase the previously created instances. They are all held in memory. You can try it out even in your own demo. Just set multiple to no call so many popovers you want and then check out this line in the browser's console:

    $(".webui-popover-content");

You will see that all the instances are still there. Imagine what happens when you have 400+ of them ;)

So I'm using this little helper code to remove the other instances except the current one. This is still not the best approach because the user have to hover over the popover - so it's not working on touch devices and for all users who behave differently.

	$('.webui-popover').live('mouseenter', function(){
		$(".webui-popover").not(this).remove(); 
	});

**Comment by sandywalker** [comment]
I can optimise the hide method of the plugin, when cache is set to false, hide method will remove the target.
I'm not very sure that it is really the dom tree kill the performance,I tested 500+ popovers with safari and chrome browser on my macbook pro , but could't found the performance get slow. 
You mean your helper code can avoid this situation?  If so I'll update the popover as soon as possible.

**Comment by Hexodus** [comment]
You're completely right this is the dom tree. My domtree has a lot of content inside before calling the popovrs and my popovers have a lot of stuff inside so the dom tree is growing really fast. 

After all the final solution was easy. I simply placed the helper code inside this function like this:

	$(this).webuiPopover({
		type:'async',
		url:'my-ajax-file.php',
		content:function(data){
		    $(".webui-popover").not(this).remove(); 
		  return data;
		}
	});

And yes, it prevents the dom tree growth so no slowdown happens any more ;) You might consider giving it a new option like "unique" because 

By the way a big 'thank you' for this very, very usefull tool ;)

**Comment by sandywalker** [comment]
Nice suggestion, I'll consider.
