### ISSUE TITLE
CDN support

### ISSUE THREAD

**Issue by KrishnaPG** [sandywalker/webui-popover#115]
This is good work. Please make it available on CDN (such as JSDelivr)

For example, adding to JSDelivr is simple and it automatically updates whenever version changes: https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md

**Comment by sandywalker** [comment]
The plugin is now avavilable on JSDelivr CDN from version 1.2.1 .
Thanks very much for your nice suggestion!
