### ISSUE TITLE
One little bug when have two or more popover

### ISSUE THREAD

**Issue by phc-itt** [sandywalker/webui-popover#117]
When have two or more popover. 
- From 1st popover: it's ok. because i can focus this.
- From 2nd popover: when I click to this popover, It is hidden, it wrong.

Demo at: http://sandywalker.github.io/webui-popover/demo
-When click to 2nd popover, I cannot focus to it.
Sorry for my bad english too

**Comment by costa974** [comment]
Di you solve it in some way? It' not a little bug.

**Comment by sandywalker** [comment]
I found this bug and  will solve the problem soon.

**Comment by phc-itt** [comment]
Thank you so much

**Comment by sandywalker** [comment]
The bug is fixed,please download the new version and test it.
Thanks.

**Comment by costa974** [comment]
Wonderful. Thanks.

**Comment by costa974** [comment]
Unfortunately it doesn't seem to work on Samsung tablet default browser, on Chrome it works. I'm using a Galaxy Tab 3. The popovers appear on touch, but disappear immediately.

**Comment by sandywalker** [comment]
Sorry, I don't know why this happen,with no Galaxy Tab 3 in my hand, I tested the plugin in chrome dev-tools, and my iPhone and some Android devices,it just works fine.

**Comment by phc-itt** [comment]
Wonderful. Thanks.
