### ISSUE TITLE
multiple urls on asnyc mode

### ISSUE THREAD

**Issue by dcalixto** [sandywalker/webui-popover#118]
i would like to pass a couple of list urls to popover. and one of then is dynamic. is possible? 

thank's

**Comment by sandywalker** [comment]
You mean you want to  pass a callback function to the url option?

**Comment by dcalixto** [comment]
i mean for exemple:
1-"/favorites/"
2-"/feedbacks/"
3- "/users/username/"

no i would like just to pass the 3 urls on the same script and pass or get the username to popover.

**Comment by sandywalker** [comment]
You can set the url by data-attribute ,for example: 
```html
<a href="#" data-url="your/url" >...
<a href="#" data-url="your/other/url" >...
```

**Comment by dcalixto** [comment]
that's it. thank you very much!
