### ISSUE TITLE
Multiple pop-overs on page, incorrect behaviour when user clicks on popover area

### ISSUE THREAD

**Issue by alexmohr1966** [sandywalker/webui-popover#119]
When popover is attached to multiple elements on page, any popover opened subsequently the first one closes when the user clicks INSIDE the pop-over content area. You can replicate the issue on your own demo page: click one popover element, close it by clicking anywhere OUTSIDE the popover element, open another popover, click INSIDE the popover and it wrongly closes. I would really appreciate if you could address this issue as this bug unfortunately renders your otherwise very good component useless for any dynamic user input scenarios.

**Comment by sandywalker** [comment]
Yes, I found this problem the same as #117  and I'll fixed it soon!

**Comment by sandywalker** [comment]
The bug is fixed, Thank you for point it out.

**Comment by alexmohr1966** [comment]
Thanks for your prompt remedy.

Regards,
Alex
