### ISSUE TITLE
Reposition popover if height or width changes

### ISSUE THREAD

**Issue by synapse** [sandywalker/webui-popover#120]
Hi, I mainly use your popover in Angular apps where usually you have some dynamic content that shows or hides. The problem is that when the height of the content changes the arrow moves with it.
Is there a way to make it stick in the original position?

Check attachment

![popover](https://cloud.githubusercontent.com/assets/71137/11383511/edeb2812-9308-11e5-9190-4735d07327da.gif)

**Comment by synapse** [comment]
After further investigation I think is a CSS problem. The arrow stays at 50% of the top so yeah, height increases so is the mid section.

**Comment by sandywalker** [comment]
Greet, thanks very much for your advice, I'll do more test with this situation and make sure this problem is solved.

**Comment by sandywalker** [comment]
This problem is solved ,Thanks very much!

**Comment by synapse** [comment]
Hello Sandy, how did you solved it in the end?
