### ISSUE TITLE
Double click on manual trigger

### ISSUE THREAD

**Issue by lmcsheff** [sandywalker/webui-popover#122]
Hi, I notice that double clicking on a manual trigger opens and closes the popover, which can cause issues as it does not fire the hidden callback. Any ideas as to handle this?

Tahnks

**Comment by Edddy** [comment]
I guess the problem it's that the first click it's interpreted as open and the second it's a click outside the popover and it closes it.

Workarounds:
1. Setting dismissible: false, to avoid being closed on the second click
2. setting trigger:'manual' and handle the clicking yourself.
