### ISSUE TITLE
Disable a popover and re-enable it again

### ISSUE THREAD

**Issue by polgiron** [sandywalker/webui-popover#123]
Hi, would be amazing if we could disable and re-enable a popover with:

$element.webuiPopover('disable');
$element.webuiPopover('enable');

In order to achieve that we need to destroy it and create it again (if I'm not wrong).

Thanks

**Comment by Edddy** [comment]
You can achieve the same results setting `trigger:'manual'` and doing nothing manually to "disable" it, and then  `trigger:'click'` to re-enable it.
