### ISSUE TITLE
Styling the close button

### ISSUE THREAD

**Issue by Hexodus** [sandywalker/webui-popover#125]
I find it very inconvenient to style the close button. There is a hardcoded "x" character - that's the reason why. It would be much better when instead of this you could use a css only solution. Then overrides via css become possible. 

This css code adds the "x":

    .webui-popover-inner .close:after {
      content: "x";
      width:0.5em;
      height:0.5em;
      padding: 4px 8px;
      position: relative;
    }

**Comment by sandywalker** [comment]
Excellent, I've  removed hardcoded "&times;" and used the css solution which you provided.
Thank you !

**Comment by Hexodus** [comment]
Thanks ;)
