### ISSUE TITLE
Trigger disapears after popover is closed... how to keep visible?

### ISSUE THREAD

**Issue by gnickoloff** [sandywalker/webui-popover#129]
If you have a minute to help me out, I am still having a problem with the element that triggers the popover being set to "display: none" after the popover is closed. I'd like the visitors to the site to be able to display the popover more than once if they wish to. 

Where/how do I prevent that from happening?

This line:
`<a href="#pop_<?= $id ?>" id="popover<?=$id?>" style="display:inline-block"><i class="icon-info"></i></a> `

becomes:
`<a href="#pop_<?= $id ?>" id="popover<?=$id?>" style="display: none"><i class="icon-info"></i></a>`			

Thanks!

**Comment by sandywalker** [comment]
I don't know why this happened in your situation ,The 'hide' method of the popover will not hide the trigger element.

**Comment by gnickoloff** [comment]
I can't figure it out. My guess is that the theme uses a highly customized
version of Bootstrap.js, and there could be some interference because of
that.

For this project, due to time constraints, I've had to move on to another
solution, but I will be using your work on other projects in the future. I
like the extended capabilities that it has.

Thanks.

On Thu, Jan 7, 2016 at 9:09 PM, Sandy Duan <notifications@github.com> wrote:

> I don't know why this happened in your situation ,The 'hide' method of the
> popover will not hide the trigger element.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sandywalker/webui-popover/issues/129#issuecomment-169866047>
> .
>



-- 
--Greg.

No trees were destroyed in the sending of this message, however, a
significant number of electrons were terribly inconvenienced.

**Comment by javarich** [comment]
In case might help someone else, I had this same issue, turned out had prototype.js included on the same page. Once removed prototype, issue went away.
