### ISSUE TITLE
Fade in?

### ISSUE THREAD

**Issue by artsyca** [sandywalker/webui-popover#13]
I've had success adding this simple CSS rule to make the popover fade in:

    .webui-popover {
      -webkit-animation: fadein 0.4s; /* Safari, Chrome and Opera > 12.1 */
         -moz-animation: fadein 0.4s; /* Firefox < 16 */
          -ms-animation: fadein 0.4s; /* Internet Explorer */
           -o-animation: fadein 0.4s; /* Opera < 12.1 */
              animation: fadein 0.4s;
    }

    @keyframes fadein {
        from { opacity: 0; }
        to   { opacity: 1; }
    }

    /* Firefox < 16 */
    @-moz-keyframes fadein {
        from { opacity: 0; }
        to   { opacity: 1; }
    }

    /* Safari, Chrome and Opera > 12.1 */
    @-webkit-keyframes fadein {
        from { opacity: 0; }
        to   { opacity: 1; }
    }

    /* Internet Explorer */
    @-ms-keyframes fadein {
        from { opacity: 0; }
        to   { opacity: 1; }
    }

    /* Opera < 12.1 */
    @-o-keyframes fadein {
        from { opacity: 0; }
        to   { opacity: 1; }
    }

Just thought you might consider adding fade-in/out as an option?

via: http://stackoverflow.com/questions/11679567/using-css-for-fade-in-effect-on-page-load

**Comment by Hexodus** [comment]
+1 for this - the current fadein effects seems not to work. I tested this approach and it works fine.
