### ISSUE TITLE
PopUp div disappears after triggering 4-5 times.

### ISSUE THREAD

**Issue by smartsites-dev-n01** [sandywalker/webui-popover#131]
Hi,

I have the problem that, the pop will be empty after 4-5 times triggering  from 4 different trigger for same div with selector method.

hera is my code looks like.
``` html
<div class="myLink">
<a href="#" class="trigger">trigger 1</a>
<a href="#" class="trigger">trigger 2</a>
<a href="#" class="trigger">trigger 3</a>
<a href="#" class="trigger">trigger 4</a>
</div>
<div class="myPopup">
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
</div>

<script>
$('.trigger').webuiPopover({url:'#myPopup'});
</script>
```
First 2-3 times the popup shows 'lorem ipsum..' text but after that only one <a> triggers popup with text  but, others trigger the empty popup.

Thanks,
Bishwaksen.

**Comment by tlangreh** [comment]
I'm experiencing this same issue. I can reproduce it after a single click off of the popover onto another area (one which does not result in showing the popover), then click to open the same popover again. It shows up blank the second time for that popover and also blank for all other popovers in my list as indicated by Bishwasksen.

**Comment by tlangreh** [comment]
Although I'm certain that I tried this before, it could have been a combination of different things, but setting cache:false nearly fixes it. However, in IE, clicking on a target to open the popover, then clicking it again to close it (or clicking elsewhere to launch no popover), then clicking the same target to re-open, still seems to result in the div being blank. However, cache: false improved the issue significantly.

**Comment by sandywalker** [comment]
This bug is fixed , you can download the code from github, I'll make the release package when I've finish to fix the other bugs.

**Comment by tlangreh** [comment]
Thanks Sandy :)
