### ISSUE TITLE
Issue with 1.2.3 - popovers appearing all at once and going mad

### ISSUE THREAD

**Issue by Hexodus** [sandywalker/webui-popover#133]
I realized that `placement: 'vertical'` is not working in v1.1.3 so I just tried out the new version 1.2.3. The big suprise is that all popovers are created visibly on screen an then poping up one by one without being hovered over. This didn't happen in the v1.1.3 so I assume that something has changed or is broken. Here's my code for calling the popovers. Maybe it's relevant to this issue.

    $('.infohover').each(function(index) {
      bookid = $(this).attr('id');

      // calculate width dependent on document width

      max_width = 720;
      min_width = 300;
      current_width = parseInt($(document).width()*70/100);

      if(current_width > max_width)
        popover_width = max_width;
      else if(current_width < min_width)
        popover_width = min_width;
      else
        popover_width = current_width;

      $(this).webuiPopover({
            type:'async',
            url:'my-ajax-file.php?ID='+bookid,
            content:function(data){
                  $(".webui-popover").not(this).remove(); 
                return data;
            },  
            async: {
                before: function(that, xhr) {
                },
                success: function(that, data) {
                   fooFoo(); 
                }
            },
            title:'',
            style:'inverse', 
            closeable: true,
            multi: false,
            placement: 'vertical',
            trigger:'sticky',
            width: popover_width,
            animation:'fade',
            cache:false
          });

    });

I just added a [JS BIN demonstration] (https://jsbin.com/cajeyelone/edit?html,css,js,output)

Unfortunately there is no cdn file for the 1.1.3 otherwise I would show you how this version looked a like.
![popover_issue](https://cloud.githubusercontent.com/assets/243039/12078729/b709665e-b21d-11e5-9150-1c9746b69446.jpg)

**Comment by sandywalker** [comment]
The value of  trigger option  in your code is set to 'sticky', this means that the popover will always show on screen after it is created. You can set the value with 'hover' or just leave it with default  value 'click'.

**Comment by Hexodus** [comment]
Oh thanks a lot - this was indeed the 'sticky' option. Now it works properly.
