### ISSUE TITLE
This is not an issue but I really need help about this

### ISSUE THREAD

**Issue by jsgspotifi** [sandywalker/webui-popover#134]
// Example Webui Popover Pop with Table
        // ------------------------------------
        (function () {
            // BUTTON
            var tableContent = $('[id^="examplePopoverTable"]').html(),
                    tableSettings = {
                        title: 'POINT SYSTEMS', 
                        content: tableContent,
                        width: 500
                    };

            // TABLE
            $('#examplePopWithTable').webuiPopover($.extend({}, defaults,
                    tableSettings));
        })();
 
I have like 20 buttons with corresponding table popovers and each containing different info.
How can i be able to access each info to the table, thru this code? It happens that it only access the first table. Sorry Im kinda new to this. This would be a great help. thank you so much

**Comment by sandywalker** [comment]
There are two ways can solve your problem. 
1. you can put the table element next to your button and set class with 'webui-popover-content'
```html
<a href="#" >shop pop</a>
<div class="webui-popover-content">
	<p>popover content</p>
</div>
```
This situation, you don't need to set content value anymore.

2. set the callback function to content option, in callback function you can specify the table element associate with your button element.
