### ISSUE TITLE
Not working on first time hover

### ISSUE THREAD

**Issue by kapilpatel** [sandywalker/webui-popover#136]
Its a really good library for pop-over.

I'm using pop-over in ng-repeat (ANGULARJS). It is not working on first time hover, working fine on second time.

**Comment by sandywalker** [comment]
Sorry,I haven't tested this plugin with angularjs. Is your problem solved?

**Comment by srikanthhashmap** [comment]
I am also facing the same issue not working for first time

**Comment by ErHu1993** [comment]
you need add this code $(el).webuiPopover('show')  after  $(el).webuiPopover(options)
