### ISSUE TITLE
After webuiPopover('hide') Uncaught TypeError: Cannot read property '_opened' of undefined

### ISSUE THREAD

**Issue by xmon** [sandywalker/webui-popover#137]
Webui open popover with a form.

The form is submitted by ajax, controlling the answer, if correct, I close the webuipopover, "webuiPopover('hide')".

here all right, but when you click anywhere on the web, console received:
```Uncaught TypeError: Can not read property '_opened' of undefined```
line 653:
```if (pop._opened) {```

Any idea to solve it?

thanks a lot

**Comment by sandywalker** [comment]
I tried some test with this situation, everything just work fine. So I can't find the reason,but I add the undefined check in the if statement just to avoid the typeError. 
I pulled the source code to the repo,You can try the code to see if the plugin works OK!
Thanks!

**Comment by zendre4** [comment]
+1

**Comment by zendre4** [comment]
Latest version work for me ! thanks

**Comment by xmon** [comment]
testing and solved at version 1.2.18

thanks
