### ISSUE TITLE
delay option doesn't work?

### ISSUE THREAD

**Issue by artsyca** [sandywalker/webui-popover#14]
I can't seem to make the tooltip delay on hover even if I set the delay option to a high number..

**Comment by u-nik** [comment]
Set hide delay to 1 may help.

The delay is defined by the following line of code:
```javascript
return this.options.delay.hide||300;
```

You can see the problem, i think. If the hide value evaluates to false, 300 is taken for the delay.

**Comment by crisk** [comment]
you' re absolutely right! thank you!

**Comment by sandywalker** [comment]
Oh,That's the code bug, the value 0 should take effect, I'll fix it.

**Comment by sandywalker** [comment]
The problem is solved, you can set delay to 0 now.
Thanks
