### ISSUE TITLE
How to change URL when retrieving content with async?

### ISSUE THREAD

**Issue by carliros** [sandywalker/webui-popover#143]
Hello, 

I am wondering how to change the URL when using async type once the popover was started.

I tried using a function in the URL option, and also the 'before' function in 'async' option, and no success. Is it possible to do? any ideas?

Here is my [Fiddle example](http://jsfiddle.net/carliros/y64tu5bz/3/).

**Comment by sandywalker** [comment]
The default value of cache option is true,you can set the cache to false.
