### ISSUE TITLE
Relative positioning - popovers do not scroll with content

### ISSUE THREAD

**Issue by bobmash** [sandywalker/webui-popover#144]
Hi, 

Great plugin, but I have an issue with using the popover within a scrolled div container - they do not scroll relatively with the content / trigger element.

As the popovers are absolute positioned, they do not scroll with the content when they are open, they remain static; is there a way of achieving this perhaps through relative positioning etc.?

Thanks,
Liam

**Comment by phc-itt** [comment]
Hi!
Currently I am having problems like you to use them on the bootstrap's modal.
When the bootstrap's modal is opened. they will roll off document.body; This has led to the modal popup will not be open on the modal scroll is rolled.

**Comment by jeremyVignelles** [comment]
Hi,
Same problem here. I hope to have time to fix and publish a PR.
My guess is that this line is causing the issue:

https://github.com/sandywalker/webui-popover/blob/master/src/jquery.webui-popover.js#L348

I think there should be a "container" option to let you specify the scrolling content.

**Comment by jeremyVignelles** [comment]
Added a JSFiddle to reproduce my issue : https://jsfiddle.net/1x21rj9e/

**Comment by mattbhenley** [comment]
@sandywalker is this still a known issue? I am experiencing the same thing but haven't been able to find a solution. @jeremyVignelles demo above, I don't see the issue being fixed. Any help is appreciated!
