### ISSUE TITLE
Popover not hide in mobile devices

### ISSUE THREAD

**Issue by jayeshtank** [sandywalker/webui-popover#145]
Hi,

I have shown popover on link on 'hover' event. it is working fine in desktop browser.
Now in mobile devices, If I click on that link it will open the popover, but when I click on outer area it will not closing popover automatically. If we check from desktop browser mobile view, it is working fine but not in actual device.(problem in iPhone)

I am using Firefox 44.0.2. And also position of popover not updating while rotate my mobile. orientation problem.

Is there any way to hide popover automatic in mobile device?

Thank you in advance.

**Comment by sandywalker** [comment]
This problem should be fixed after version 1.2.6, please go and check.

**Comment by george-norris-salesforce** [comment]
This is still a problem
