### ISSUE TITLE
Pull data- values when constructing url?

### ISSUE THREAD

**Issue by seanford** [sandywalker/webui-popover#146]
Is it possible to construct the url from data attributes in the target object.  Below is a simplified example of what I'm trying to do.  My actual code will use a calculation, based on values pulled from input fields on the page, so pre-populating the data-url value as suggested in other issues is not possible.

While` $(this) `works within the content function, it does not in the code below.

Thank you.

`	$('.row-note-icon').webuiPopover({
		type: 'async',
		url: '/v4/_inc/ajax/aqs4Note.cfm/solNbr/' + $(this).data('solnbr'),
		content: function(data){
			return data;		
		},
		placement: 'auto',
		width: 'auto',
		height: 'auto',
		trigger: 'click',	
		animation: null,
		cache: false,
		multi: false,
		arrow: true,
		title: 'AQS Notes:',
		closeable: false,
		padding: true,
		backdrop: false,
		dismissible: true,
		autoHide: false,
		offsetTop: 0,
		offsetLeft: 0,
    	onShow: function($element) {}, // callback after show
    	onHide: function($element) {}, // callback after hide		
	});`

**Comment by Edddy** [comment]
No, the url value will be initialized with the value at initialization moment. Try using the before event to change the url before the async call

From the docs:
```
async: {
        type:'GET', // ajax request method type, default is GET
        before: function(that, xhr) {},//executed before ajax request
        success: function(that, data) {}//executed after successful ajax request
        error: function(that, xhr, data) {} //executed after error ajax request
    },

```

**Comment by seanford** [comment]
Yes, I got it working…

I used before: and that.$element to pull the data attributes I needed and re-set the URL at settings.url

I’m replying to help anyone else that may need to do the same.

**Comment by seanford** [comment]
Now that I look at my code, I think I had to expose the settings element in the source in order to pull this off.

before: function(that, xhr, settings) {
    // do stuff here to get data for new url

    // then set url
    settings.url = 'new url';
}

**Comment by Edddy** [comment]
Great. Please close the issue so we help Sandy cleaning up the issues list.
