### ISSUE TITLE
option cache: false does not destroy the element

### ISSUE THREAD

**Issue by quackes** [sandywalker/webui-popover#147]
when i set cache: false in the creating options, the popup element does not get destroyed when hidden. 
Test-Fiddle: [JSFiddle](https://jsfiddle.net/a0bvwr5s/) (CSS omitted)

From the code I assume the option is just not completely implemented, because the destroy-method is never called.

**Comment by harlet** [comment]
The code from cdn is not the lastest versions, is the lastest release witch is alot behind.  :)

**Comment by quackes** [comment]
Even in the source code the destroy method ist never called. I updated my [fiddle](https://jsfiddle.net/a0bvwr5s/1/) so that it loads from dist in master, and the behavior is the same.

**Comment by sandywalker** [comment]
The destroy method can  not be called directly in hide method, because this will destroy the event handler on trigger element too. 
I'll fix cache problem in next version, please wait.

**Comment by sandywalker** [comment]
This bug is fixed, Thanks.
