### ISSUE TITLE
Document ON Click and $(this).webuiPopover issue

### ISSUE THREAD

**Issue by Join-Git-Hub** [sandywalker/webui-popover#149]
**Example 1**
`<p` class="bar">Google</p>
`<p` class="bar">Twitter</p>
`<p` class="bar">Facebook</p>

`<script>`
     $('.bar').webuiPopover({
      content:'Content',
      placement:'right'
  	});
</script>

**Example 2**

`<p` class="foo">Google</p>
`<p` class="foo">Twitter</p>
`<p` class="foo">Facebook</p>

`<script>`
	$(document).on('click', '.foo', function(){
		$(this).webuiPopover({
      	content:'Content',
      	placement:'right'
		});
	});
</script>

The first example works as expected ... everything fine

The second example does not work as desired.
You have 2 times click on the link, so the popup appears.

Is there a problem, a solution?

Thank you so much!

**Comment by gpiccolo** [comment]
You can try to set manual trigger for the popover 
```
$(this).webuiPopover({
  content:'Content',
  placement:'right',
  trigger: 'manual'
});
```
and successively show the popover in this way 

`$(this).webuiPopover('show');`

for me worked well.
