### ISSUE TITLE
RTL Support ?

### ISSUE THREAD

**Issue by aymanstar** [sandywalker/webui-popover#150]
Hello , can you provide RTL Support Please for multi Languish website that use LTR/RTL BASED ON user setting ?

**Comment by sandywalker** [comment]
I'm very glad to add this feature, but I don't know how to implement it. If you have some suggestion please leave a comment.

**Comment by harlet** [comment]
Is about the css. I think you can add a class named RTL to the main div on show and in css some settings.

**Comment by aymanstar** [comment]
its about css , also element position   , 

check this images 
<img width="291" alt="screen shot 2016-05-03 at 7 34 32 pm" src="https://cloud.githubusercontent.com/assets/364872/14990671/511a7eb6-1166-11e6-8a58-df8dbc6062f3.png">
<img width="646" alt="screen shot 2016-05-03 at 7 35 27 pm" src="https://cloud.githubusercontent.com/assets/364872/14990672/5151231c-1166-11e6-9b02-f0310ce72d5c.png">

the english one is LTR , Page start from left , put the second is RTL , page start from right , but , postion is incorrect

**Comment by sandywalker** [comment]
I've added the 'direction' option for the RTL layout, default is null, you can set the value with 'rtl' for RTL
