### ISSUE TITLE
Same link!

### ISSUE THREAD

**Issue by dcalixto** [sandywalker/webui-popover#151]
Hi, i'm making a loop over a category links and use the popover to get the subcategory links. but the popover did not get the new links. when i hover over other categories. the popover still showing on the content the links of the first category.

exemple:
    <% @categories.each do |category| %>
      <%= link_to  c.name,  category_path(:id => c.id), :class =>"3"  %>
      <% g.subcategories.first(5).each do |s| %>
<div class="hide">
      <%= link_to   s.name, sub category_path(:id => s.id)  %>
</div>
          <% end %>
      <% end %>

the popover:

$(document).ready(function() {
$('.3').webuiPopover({

type: 'html',
  url:'.hide',
  trigger: 'hover',
  padding: false,
  cache: false,

});

});

**Comment by sandywalker** [comment]
In this situation, you can set the url on data-attribute (data-url=...) on trigger elements in loop code.
