### ISSUE TITLE
loading.gif is missing from CDN

### ISSUE THREAD

**Issue by meliezer** [sandywalker/webui-popover#153]
Hello,
I'm using https://cdn.jsdelivr.net/jquery.webui-popover/1.2.5/jquery.webui-popover.min.css
and the browser reports HTTP 404 for
https://cdn.jsdelivr.net/jquery.webui-popover/img/loading.gif

Best regards,
Menashè

**Comment by sandywalker** [comment]
Oh,I forgot upload this file to CDN,I'm trying to fix this problem.

**Comment by meliezer** [comment]
Thank you. I see also an error for ../images/arrow_right_peppermint.png

**Comment by sandywalker** [comment]
I added the gif file and pulled the request to the jsdeliver,please  wait some time.

**Comment by meliezer** [comment]
Thank you, but loading.gif is still missing from version 1.2.8:
 jquery.min.js:3 GET https://cdn.jsdelivr.net/jquery.webui-popover/img/loading.gif 404

**Comment by sandywalker** [comment]
@meliezer It's my mistake, I have pulled the wrong request to the jsdelivr. Now I'm waiting the jsdelivr to merge my new pull request.

**Comment by sandywalker** [comment]
loading.gif is available in version 1.2.12!
