### ISSUE TITLE
How to destroy webui-popover

### ISSUE THREAD

**Issue by kingRayhan** [sandywalker/webui-popover#155]
I activate webui-popover this
```
$(.something).webuiPopover()
```
when I don't put anything in `title` and `content` , a blank popover is showed
![](http://i.imgur.com/SUAkuui.png)

can I completely hide this blank popover when I don't give anything in the `title` and `content` ?
or can I destroy webui-popover behavior from an element in anycondition like this ?
```
 $(.something).destroyWebuiPopover()
```

**Comment by meliezer** [comment]
.webuiPopover('hide')
.webuiPopover('destroy')

**Comment by kingRayhan** [comment]
Thanks :)

**Comment by oninross** [comment]
Saved my butt...thanks for this
