### ISSUE TITLE
Show pop-up only after the setContentASync

### ISSUE THREAD

**Issue by harlet** [sandywalker/webui-popover#158]
Hi,

I have some trouble in keeping the pop-up from showing if the type is async, and show it only after a succes callback, or error...

What i've tried:

`
if (!this.isAsync()) {
 $target.show()
}
`

in the show function.

**Comment by Edddy** [comment]
Why don't you put the popover in manual and show it in the callback? 

```
 //Initailize
 $('a').webuiPopover({trigger:'manual'});
...

 //Show it in the callback
 $('a').webuiPopover('show');

```
