### ISSUE TITLE
LESS - Prefix variables with popover (collisions)

### ISSUE THREAD

**Issue by BillyBlaze** [sandywalker/webui-popover#163]
Hi,

I see you have a less file inside your src folder, and that would be awesome for people working with less (e.g. build task with autoprefixer)

However I am a bit worried about naming collisions, that could interfere with global variables.

```
@border-radius-base:        4px;
@border-radius-large:       6px;
@border-radius-small:       3px;

@font-size-base:          14px;
@font-size-large:         ceil((@font-size-base * 1.25)); // ~18px
@font-size-small:         ceil((@font-size-base * 0.85)); // ~12px


@close-size:                16px;
@close-color:               #000;
```

Could this be changed into?
```
@popover-border-radius-base:        4px;
```

This would also give us the ability to overwrite the default variables after loading your default less file.

*edit*
Perhaps it also a good idea to prefix the keyframe rotate with popover.

**Comment by sandywalker** [comment]
OK,I'll fix this.

**Comment by BillyBlaze** [comment]
Awesome thanks!

**Comment by sandywalker** [comment]
I've already changed the variable names, you can get  the newest version.
