### ISSUE TITLE
Clicking on the link brings to the top of the page when the trigger is set to "hover"

### ISSUE THREAD

**Issue by andrius-senulis** [sandywalker/webui-popover#164]
Dear contributors,

Clicking on the link brings to the top of the page when the trigger is set to "hover". It seems to be solved for the case when the trigger is "click".

Cheers,
Andrius

**Comment by sandywalker** [comment]
This is the browser's default behaviour, You can handle the click event yourself to avoid this behaviour,or just make the href="javascript:" on link tag.
