### ISSUE TITLE
svgelement.offsetwidth

### ISSUE THREAD

**Issue by suhailc12345** [sandywalker/webui-popover#165]
offsetWidth property of svg elements is deprecated in all browsers and due to this the position of popover is not working properly

**Comment by sandywalker** [comment]
Thank you for reminding，I've fixed this bug in version 1.2.11.

**Comment by gregblass** [comment]
Just ran into this. Searched GitHub issues, found this, upgraded, and boom - fixed. Thank you @sandywalker !
