### ISSUE TITLE
Placement bugfix from 1.2.8 introduced a new bug

### ISSUE THREAD

**Issue by nomadOnWeb** [sandywalker/webui-popover#166]
Hello !
First, thanks for this great plugin ! It was exactly what I needed, far better than bootstrap popover which have many issues when we want to go further than a simple popover.

Unfortunately, the last update (1.2.8) introduced a new bug by improving the previous placement bugfix.
You can easily see the bug on this fiddle : https://jsfiddle.net/tu4ttweq/6/
There is no special css, the thing is :
Scroll down a bit and click on the trigger, you'll see the popover popping in a wrong position.
It seems like the "top" property is set regarding of the viewport and not the main container (which is the default one on my fiddle).

PS: I will continue with 1.2.7 for now, I didn't see any issue on this one, at least for my purpose (and for now)

**Comment by maryisdead** [comment]
For me, this isn't even working with 1.2.7. I forked @nomadOnWeb's fiddle and tweaked it a bit: https://jsfiddle.net/maryisdead/t0jskhch/

Just scroll the square to the top or bottom edge. The tooltip will always be placed at the bottom and thus be hidden when the square is at the bottom. Works fine if I add [1.2.6 from jsDelivr](http://www.jsdelivr.com/?query=webui-popover).

**Comment by sandywalker** [comment]
This bug is fixed in version 1.2.9.
Thanks!
