### ISSUE TITLE
Timeout hides freshly opened popover

### ISSUE THREAD

**Issue by BillyBlaze** [sandywalker/webui-popover#174]
I currently have 2 buttons with a popover next to eachother, if you are quickly by pressing between the buttons, then the popover will open but after it has been shown it will be hidden again (and you need to click twice to re-open it). Can this time of the timeout be an option? so we can set it to 0ms?

Culprit code: https://github.com/sandywalker/webui-popover/blob/master/dist/jquery.webui-popover.js#L238

**Comment by Edddy** [comment]
Setting it to 0ms will have side effects. If you are using the plugin only for this, change it in your code, if not, maybe you should open and close the popover programmatically to achieve the effect you want.

**Comment by BillyBlaze** [comment]
Setting it to 300ms hardcoded will have side effects too. We're using the plugin through the whole application with bower during deploy. So no, I can't and won't change this code, beside it's a **really really** bad practice.

Also if it's an option, We can also set it to 10, or 50ms, or whatever works best, while you can still enjoy your default 300ms.

**Comment by sandywalker** [comment]
I've already change the hardcode to the option 'delay.hide'. Thanks your advice.
