### ISSUE TITLE
Feature request: Hide/Destroy all popovers

### ISSUE THREAD

**Issue by MickL** [sandywalker/webui-popover#175]
Hey,

is there a possibility to hide all popovers?
I want to hide them when starting to scroll ...

Greetings

**Comment by Edddy** [comment]
Use: 
`$(".popover").webuiPopover('hide');`

**Comment by MickL** [comment]
I need something like `each webuiPopover('destroy')` but the popover is attached to different handles so i would have to target each dom element...

A global function would be nice to remove all popovers.

**Comment by sandywalker** [comment]
I've added this feature.
