### ISSUE TITLE
click handlers prevent other events from firing

### ISSUE THREAD

**Issue by dmeehan** [sandywalker/webui-popover#178]
I'm wondering how the click events to show and hide the popovers are created. It seems that right now, the way it is coded prevents other click handlers from being attached the the same trigger (e.stopPropagation ?) Is it possible to refactor the code so that the other events are not cancelled and this plugin can play nicely with other code? I'd be happy to take a crack at it if you can point me in the right direction.

Thanks.

**Comment by Edddy** [comment]
Having several events on the same click seams very weak, and subject to problems. If you have an edge case, you should implement the events and fire the popover manually when you need it.

**Comment by dmeehan** [comment]
Yes, I agree that it generally you would want a single event on a click, but I think there are legitimate use cases for more than one (particularly when you are composing more than one plugin). I'm not sure what is occurring in the code that is disabling subsequent events, but see this for the problems with using e.stopPropgation: https://css-tricks.com/dangers-stopping-event-propagation/

**Comment by lukasbesch** [comment]
I also ran into issues. I was using `trigger: 'manual'` to attach my own event listeners to the popup. It worked but only for non-mobile devices and I think I found the origin:
````js
//init the event handlers
if (this.getTrigger() === 'click' || isMobile) {
    this.$element.off('click touchend').on('click touchend', $.proxy(this.toggle, this));
} else if (this.getTrigger() === 'hover') {
    this.$element
        .off('mouseenter mouseleave click')
        .on('mouseenter', $.proxy(this.mouseenterHandler, this))
        .on('mouseleave', $.proxy(this.mouseleaveHandler, this));
}
````
From: https://github.com/sandywalker/webui-popover/blob/ef21820c815e124a1429eb04a78d3f3183c4e58d/src/jquery.webui-popover.js#L154

Probably it should by something like


````js
if (this.getTrigger() !== 'manual') {
	//init the event handlers
	if (this.getTrigger() === 'click' || isMobile) {
	    this.$element.off('click touchend').on('click touchend', $.proxy(this.toggle, this));
	} else if (this.getTrigger() === 'hover') {
	    this.$element
	        .off('mouseenter mouseleave click')
	        .on('mouseenter', $.proxy(this.mouseenterHandler, this))
	        .on('mouseleave', $.proxy(this.mouseleaveHandler, this));
	}
}
````

**Comment by MickL** [comment]
@sandywalker i guess this issue is not fixed:
When binding click to the same element which got a popover, the other clicks are not working. Instead you will always see the popover instead.

Example: Showing a error-message popover for a fileupload-button.

Solution: propagation should not be stopped! (Maybe as a option)
