### ISSUE TITLE
Unable to target html elements within the webui-popover with jquery

### ISSUE THREAD

**Issue by nick2687** [sandywalker/webui-popover#18]
Trying to target the content that is added within the popover, however it seems like the plugin might be preventing it? 

The .on function should work for this but doesn't...

$("body").on("click",".label",function(e) {
    alert("Testing");
});

**Comment by Levino** [comment]
@nick2687 Has this been solved for you? I cannot get it to work.

**Comment by psinghania** [comment]
@sandywalker I am using this as my content in the popover:

var emailBody = <div id="emailStoryBox">
	<form class="form-horizontal" method="POST" action="" id="shareViaEmailForm">
		<input type="hidden" name="itemid" value="abc"/>		
		<input type="text" class="input form-control" name="email" placeholder="Friend's Email Address"/>
		<br />
		<input type="text" class="input form-control" name="subject" placeholder="Subject" value="My title"/>
		<br />
		<textarea rows="3" cols="50" placeholder="Your note to go along with the text." name="note" class="form-control"></textarea>
		<br />
		<button type="submit" class="btn btn-primary" onclick="sendSharingEmail(); return false;">Send Email</button>
	</form>
</div>

and this is how I am creating popover:
$('#shareEmailButton').webuiPopover({
		placement : 'top',
		type:'html',
		content : function() {			
			return emailbody;
		}
	});

But when I click on input or textarea, nothing happens and I cannot edit them.
Can;t seem to get it working.

**Comment by sandywalker** [comment]
The plugin updated so much, this problem should be fixed

**Comment by framelita** [comment]
Hi @sandywalker. It still didn't work.

**Comment by quadrifoliumclover** [comment]
Had the same problem trying to reach inputs inside popover in my modal.
Changing 'container' option to '.modal-body' for correct events delegation did the trick for me.
Found answer here: https://stackoverflow.com/a/24015585/6103499
