### ISSUE TITLE
Inserting content dynamically not working

### ISSUE THREAD

**Issue by FlyingCarpets** [sandywalker/webui-popover#182]
Hi,
I've noticed a bug (?) while trying to add content to the title of the popover which would change dynamically. The content doesn't change, although cache is set to false:
http://jsbin.com/gazibepavu/1/edit?html,js,output.
Also dismissible doesn't work in this particular case.
Is it possible to use any other options for changing the content dynamically?
thank you.

**Comment by Edddy** [comment]
You are making several mistakes in that jsbin that has nothing to do with Popover, but more with the way javascript works (too long to explain here)

Here is the working version http://jsbin.com/tecowiriba/1/edit?html,js,output

**Comment by sandywalker** [comment]
The new global method ``` WebuiPopovers.updateContent(selector,newContent) ``` can solve the problem.
