### ISSUE TITLE
'destroy' does not work on trigger 'click' after onHide at iOS

### ISSUE THREAD

**Issue by MickL** [sandywalker/webui-popover#185]
I want to show a error-message only once. After a new click it should get destroyed. I used onHide for this.

Problem: 
After onHide is executed, the popover gets removed from dom(good!). But if i click again into my handler, the popup comes back again! This seems to work in Chrome, but not on iOS (tested on iPad).

Here is my code:

```
var $thumbnail = $('#thumbnail');

$thumbnail.webuiPopover({
                title:     'Error',
                content:    msg,
                placement: 'right',
                animation: 'pop',
                trigger:   'click',
                cache:     'false',
                onHide: function() {
                        $thumbnail.webuiPopover('destroy');
                }
});
```

**Comment by MickL** [comment]
I think i found the error:
The destroy function doesn't unbinds touchend. Line 205 should be:

` this.$element.off('click touchend');`

**Comment by sandywalker** [comment]
Yes,I've updated the code. Thanks for helping!
