### ISSUE TITLE
How to change content 

### ISSUE THREAD

**Issue by letournj** [sandywalker/webui-popover#186]
Hi,

Just a question, I want to change the content of my popover : 

`$('ID').webuiPopover({content:'TEXT'})`

ID : the ID of the popover

Am I wrong somewhere ?

Thanks

**Comment by Edddy** [comment]
In ID you should put the JQuery selector of the element. It's `$('#ID')` if you want to pick from the element ID.
There are several samples in the documentation. Have you tried them yet?
