### ISSUE TITLE
Arrow not shown in Firefox when container is document.body

### ISSUE THREAD

**Issue by gabrielfin** [sandywalker/webui-popover#187]
The following commit: fbde895d21a613022f13e1c36e00d37d6e207774 broke the positioning of the arrow when using placements `left-top` and `right-top`. This happens because of the introduction of the `container` option, which by default is `document.body`. document.body.scrollTop returns always zero, because apparently the correct usage is document.documentElement.scrollTop. Therefore every calculation that uses scrollTop is wrong.

Steps to reproduce:
1) Open `demo/index.html` in Firefox and make the window small enough so that the vertical scrollbar appears.
2) Scroll down to the bottom and open the popover corresponding to `right-top` or `left-top`.
3) None of them show the arrow. Inspecting them shows that `top` has a value of `-2000`.

![screen shot 2016-07-09 at 20 29 52](https://cloud.githubusercontent.com/assets/787075/16710822/f52ee096-4613-11e6-8a6a-61e804ca66da.png)

**Comment by sandywalker** [comment]
Thank you very much for point this out and submit the cause info, I've change the code which calculate the scroll number.
```js
scrollTop = document.documentElement.scrollTop + container.scrollTop(),
scrollLeft = document.documentElement.scrollLeft + container.scrollLeft(),
```
Now the problem is resolved.
