### ISSUE TITLE
WebuiPopovers.show('#mypop'); 好像不能正常发挥作用

### ISSUE THREAD

**Issue by luckycol** [sandywalker/webui-popover#188]
不知道我写中文您能否看得懂，主要看您的头像，期望能够读得懂。
在开发中非常喜欢这个组件，用起来方便。
有的时候面对随时插入的新的 a 标签，如果按照文档说明得重新绑定。
所以我写了一段代码，虽然这看起来有点蠢：

```js
$('body').on('click', 'a[popover]', function(){
		var _this = $(this);

		if ( _this.attr('href').length > 1 ){
			_this.webuiPopover({url: _this.attr('href'), closeable:true });	//有目标指向目标
		}else{
			_this.webuiPopover({closeable:true});					//无目标找临近的，需添加webui-popover-content类
		}
		setTimeout(function(){
			_this.webuiPopover('show');
		},150);
		
	})
```

第一次点击会有150ms的延迟，第二次就好了。
看到 WebuiPopovers.show('#mypop');  确实能够解决问题，可放进去后并不生效。而且看源码好像也不支持参数的添加。
所以想能否完善.show方法，做成像alert一样能够灵活调用呢？

**Comment by sandywalker** [comment]
呵呵，我是中国人，最近有点忙没顾得上更新插件。您说的问题我会尽快修正，至于类似 alert 的方式本来想放在第二版纯 javascript 里实现的，既然您提出了，我可以尝试下在 1.x 里加入看看效果如何。

**Comment by sandywalker** [comment]
您想在动态插入的链接中的 click 事件中初始化 popover 插件，而插件本身也会拦截该链接的 click  事件，从而导致了冲突。我建议你可以采取以下三种办法来解决
1. 在插入这些链接的时候就创建并初始化 popover，这可能导致代码耦合。
2.将您代码中绑定的 click 事件换成 hover，并且并且利用 全局方法 WebuiPopovers.isCreated(selector); 判断当前按钮是否已创建了 popover，如果没有，WebuiPopovers.create(selector,options)；创建
3. 如果一定要在 click 事件中创建 popover，您需要添加 e.stopPropagation(); 防止事件传播，下面是代码示例：
```js
$('body').on('click','.added',function(e){
           var created = WebuiPopovers.isCreated($(this));
           if (!created){
              e.stopPropagation();
              WebuiPopovers.show('#added');
           }
        });
```

**Comment by Edddy** [comment]
Wow Sandy! Do you speak Chinese?

**Comment by sandywalker** [comment]
Yes, I'm   @@Chinese. 😄 @Edddy
