### ISSUE TITLE
jQuery element typecheck not working if jQuery is not globaly defined

### ISSUE THREAD

**Issue by quackes** [sandywalker/webui-popover#189]
In an Environment like webpack, jquery may not be a accessible via window.jQuery.

The type check 
`content instanceof jQuery`
  in setContent
assumes jQuery as global variable and fails in that case.

All other dependencies to jQuery seem to be handled properly with require / AMD in the factory.

Easy to work around but ugly.

**Comment by sandywalker** [comment]
Thank you for bringing this issue，I wrote this plugin was originally designed for the browser，Ignored the plug in other environments， this may be a legacy issue.
I'll try to make it more elegant, if you have some good advice please leave comment!

**Comment by sandywalker** [comment]
Since the jQuery is already imported as the $ parameter, I've change the code to 

```js
content instanceof $
```
