### ISSUE TITLE
jquery.webui-popover.min.js:9 Uncaught TypeError: d is not a function

### ISSUE THREAD

**Issue by annamalaissh** [sandywalker/webui-popover#190]
Hi,
jquery.webui-popover.min.js:9 Uncaught TypeError: d is not a function
I get this error in console and it looks to me that it is a problem with the jquery version.
My jquery version is 1.11.2. What is causing this error ?

 I tried to include the cdn sources which you have written, I got this error then..
$(...).webuiPopover is not a function

**Comment by Edddy** [comment]
Could you link to a JSFiddle with the problem?

**Comment by sandywalker** [comment]
Hi @annamalaissh , I think the problem is that the plugin need jQuery library, so make sure import the jQuery to your page first.
