### ISSUE TITLE
Bad placement

### ISSUE THREAD

**Issue by zendre4** [sandywalker/webui-popover#191]
Hello, 

For some time I have a bug with placement of the the popover. In 1.2.4 version the placement is ok but after this, the pointer of the popover is not in the good place. Example : 

When I press on the blue square a popover was displayed.

This is a functional version : 

![working](https://cloud.githubusercontent.com/assets/9673982/17392597/c2958850-5a1e-11e6-8432-880aeeb7231e.png)

And this when it's displayed after update to the last version : 

![not working](https://cloud.githubusercontent.com/assets/9673982/17392689/405a7e9e-5a1f-11e6-8911-cf7c65e1d5f7.PNG)

**Comment by Edddy** [comment]
It happens in all modern browsers?

**Comment by zendre4** [comment]
I use the last version of firefox , I have not test in Chrome...
I'll test tomorrow and I'll keep you informed.

**Comment by Edddy** [comment]
There was a problem with Firefox that was fixed days ago. Check #187

**Comment by zendre4** [comment]
I have exactly the same problem in chrome (latest version) , the placement of the pointer of the popover  is always in middle of the popover...

**Comment by zendre4** [comment]
I found the error, in last version which use, the pointer class is "arrow" and in new version the pointer class is "webui-arrow", I overload CSS and I set a custom template on the popover, that is why this display arrow in bad position, sorry for the mistake ! 

You can close this issue...
