### ISSUE TITLE
Demo page is broken when opened via https

### ISSUE THREAD

**Issue by gentoo90** [sandywalker/webui-popover#192]
https://sandywalker.github.io/webui-popover/demo/ looks like this:
![popover-demo-full](https://cloud.githubusercontent.com/assets/1297574/17412115/bfcf06f4-5a83-11e6-9604-414e899a3b61.png)

Popover doesn't work on it.

**Comment by sandywalker** [comment]
Wow, I found it. Now the bug is fixed, thank you very much!
