### ISSUE TITLE
$('.webui-popover').data('trigger-element') only works on first click

### ISSUE THREAD

**Issue by andrewtrickett** [sandywalker/webui-popover#193]
I'm trying to use the popup to edit a value on a table. I can target the triggered element to change the value by using `var clickedElement = $('.webui-popover').data('trigger-element');` and it works the first time the popup is created, but it returns undefined the second time the element is clicked.

[Fiddle](https://jsfiddle.net/q6r1u4yr/1/)

**Comment by sandywalker** [comment]
The bug is fixed,  thank you !

**Comment by andrewtrickett** [comment]
Works perfectly now, thanks 😄
