### ISSUE TITLE
failed onShow & onHide

### ISSUE THREAD

**Issue by aure369** [sandywalker/webui-popover#194]
file lines: 157, 158, 159;

see and need to change 

from:
            if (this.options.onShow) {
                this.options.onShow(this.$target);
            }

to:

            if (this.options.onHide) {
                this.options.onHide(this.$target);
            }

**Comment by sandywalker** [comment]
Sorry,I can't find the problem which you point out.

**Comment by aure369** [comment]
you fixed it...
