### ISSUE TITLE
Selector

### ISSUE THREAD

**Issue by cpinto** [sandywalker/webui-popover#197]
When using this popover with dynamic content (eg. on a single-page app), it's not possible to bind to an element that does not yet exist. Bootstrap solved it by delegating with a selector property (https://github.com/twbs/bootstrap/issues/4215), do you have any plans to support this functionality as well?

**Comment by sandywalker** [comment]
Thank you very much for providing this great idea and info,  I've always wanted to add this feature, but couldn't find a good way to solve. 
Now I added this feature to the plugin!
