### ISSUE TITLE
1.2.14 pop on hover is hidding

### ISSUE THREAD

**Issue by chanusukarno** [sandywalker/webui-popover#199]
With the latest update to `"webui-popover": "1.2.14"`  with trigger set to 'hover', popover is closing when we enter the pop even when `closeable `set to true. 
In earlier version it was fine.

**Comment by sandywalker** [comment]
Oh, thanks, I'll fix it as soon as possible!

**Comment by sandywalker** [comment]
The bug is fixed, please check out the latest version 1.2.15.
