### ISSUE TITLE
Popover arrow is not centered with plenty of space

### ISSUE THREAD

**Issue by Spartanace1024** [sandywalker/webui-popover#200]
First off just want to say that this plugin is awesome. Great work!

I integrated the plugin in a shopify theme and i'm finding that the arrow for the popover is off to the left by about 30px when choosing placement=top. I can't seem to find what is causing this issue.  

I do notice that a style tag is overriding the left:50% rule though, when i remove that style it's centered perfectly.

Thanks in advance!

**Comment by Spartanace1024** [comment]
I found the problem. For whatever reason, the newest version of jQuery (3.1.0) was causing the problem. Once I included the version of jQuery that matched version that was included in the demo [here](http://sandywalker.github.io/webui-popover/demo/#) (1.11.1) it all worked perfectly.

**Comment by sandywalker** [comment]
Oh Sorry, I've not tested the plugin with jQuery version above 2.x. I'll do some tests when I have enough time.
