### ISSUE TITLE
Global Popover Options

### ISSUE THREAD

**Issue by landjea** [sandywalker/webui-popover#202]
Is there a way to change / set the default popover config options? Like if I want `arrow: false` as **default**, instead of setting it individually on all popovers, could I set it once globally somehow? I tried standard JS global settings for functions but maybe my syntax was off.

Thanks.

**Comment by sandywalker** [comment]
I've added the new global method 'setDefaultOptions(options)', now you can change the default options with this global method.
Thanks.

**Comment by landjea** [comment]
Cool. Thanks.
