### ISSUE TITLE
Overflow hidden doesn't work

### ISSUE THREAD

**Issue by jebr** [sandywalker/webui-popover#204]
When i add a popover with a field thats big enough for the content it keeps me showing the x and y scrollbars. Also if i set overflow on hidden.

This is the config in js.

`$('#popover').webuiPopover({
        container: 'body',
        html: true,
        placement: 'bottom',
        width: 350,
        height: 120,
        backdrop: true,
        animation: 'pop',
        content: function(){
            return $('.popover-content').html();
        }
    });` 

Do you have an solution for this problem?

**Comment by sandywalker** [comment]
May be you can use css `overflow:hidden`  on css selector:  .webui-popover .webui-popover-content .
For example
```css
  .webui-popover .webui-popover-content{
     overflow:hidden;
}
```
