### ISSUE TITLE
Actions / buttons inside pop over?

### ISSUE THREAD

**Issue by waynep16** [sandywalker/webui-popover#209]
Is it possible to put buttons inside the message content ? or edit a global template to include buttons under the data-content ?

**Comment by sandywalker** [comment]
Sorry, I am not very clear about your problem. Please leave some more detail info.

**Comment by hellocosmin** [comment]
There's a `template` options that allows you to override the default popover markup: https://github.com/sandywalker/webui-popover/blob/master/src/jquery.webui-popover.js#L48
