### ISSUE TITLE
auto placement: popup could appear outside current viewPort

### ISSUE THREAD

**Issue by gboudreau** [sandywalker/webui-popover#21]
When using `auto` placement option, sometimes, especially on mobile, the chosen placement option will place part of the popup outside of the current viewPort (i.e. will require scrolling to view completely), when another placement would not.

Here's an example: http://jsfiddle.net/6gjn1fgr/7/

Just resize the result frame to 300px or so.

Clicking the red div will use `auto`, and pick right placement: ![right placement](http://f.cl.ly/items/2M3B3X3u061d1x203e03/Image%202014-11-24%20at%2015%3A02%3A08.png)

Clicking the blue div will force `top-right` placement: ![top-right placement](http://f.cl.ly/items/0T3w0k0M0u2v0I2b1n2S/Image%202014-11-24%20at%2015%3A04%3A02.png)

This occurs because the code that choose a placement when using `auto` doesn't consider the target (popup) width, in relation to `pageX` and the element width. If it did, it would notice that `pageX + elementWidth + targetWidth > clientWidth`, and wouldn't use `right`, but prefer `top-right` or `bottom-right` in that case.

If you have a preferred method on how to fix this, I could work on it, and submit a pull request. Just wanted to check how you think this should be resolved, to better serve everyone.

Thanks.

**Comment by chang-zhao** [comment]
I added a popover to my page heading with auto-right placement.
It was placed at top:-48px, i.e. popover title is off-screen.
(While it's a lot of space beneath).
Might we change top to :0 in such cases?
Thanks! Very great plugin, thank you very much.

**Comment by sandywalker** [comment]
The position bugs should be fixed by recent update, welcome to test it.

**Comment by vburlak** [comment]
@sandywalker have the same issue using latest plugin's version from repository. Does it fixed in master?

**Comment by gregblass** [comment]
+1. I was trying to use this on a site that is primarily used on mobile. Bootstrap popovers are a mess right now, which is why I was trying this - but the overflow detection is lacking. The popovers are showing up off the side of the screen.

**Comment by eggboxio** [comment]
+1. Is a new version being released soon?
