### ISSUE TITLE
Issue with isCreated method

### ISSUE THREAD

**Issue by Neymak** [sandywalker/webui-popover#210]
Hi,

There is an issue in isCreated method : 

```
var _isCreated = function(selector) {
       var created = true;
       $(selector).each(function(item) {
              created = created && $(item).data('plugin_' + pluginName) !== undefined;
       });
       return created;
};
```

"item" can't be transformed as a jQuery object because it's an index.

Can you fix it by using $(this).data(...) inside each loop ? Thx

**Comment by sandywalker** [comment]
Oh, I found it. This problem will be fixed soon!
Thank you for helping me figure this out.

**Comment by sandywalker** [comment]
This issue is  fixed.
