### ISSUE TITLE
Automatically fit width to content

### ISSUE THREAD

**Issue by alammers** [sandywalker/webui-popover#214]
Hello! I love your plugin :) Currently I'd like to create a popover that automatically fits the width to the content. I was thinking that's what width:'auto' is used for, but I still get a scrollbar in my popover.

Is there any way to make the width autofit the content or am I perhaps doing something wrong?
![image](https://cloud.githubusercontent.com/assets/13098739/20343233/da484eb2-abed-11e6-9df6-6591169397a5.png)

Is there also an option for max-height?

**Comment by sandywalker** [comment]
The plugin is fit the width automatically  by default, I guess may be some margin or padding styles in your content which cause this result.
You can set max-height in your own css style.
 Thanks!

**Comment by alammers** [comment]
Thanks! Got it to work :)
