### ISSUE TITLE
cache: false does not remove data-target from element

### ISSUE THREAD

**Issue by bazineta** [sandywalker/webui-popover#215]
When cache is set to false, the DOM element for the popover is removed from the DOM, but the triggering element still has a data-target set on it. I'd think that in this scenario, the data-target should be removed.

**Comment by sandywalker** [comment]
You are right, data-target is removed in new version.
Thanks.

**Comment by bazineta** [comment]
The code to do so in the new release appears to be commented out.

**Comment by xmon** [comment]
With version 1.2.18 still the issue.

First open, webui-popover-content has the preloader, but after first, open with webui-popover-content loaded from ajax in first opened.

this is my webuipopover config:
```javascript
$('.popover-open').webuiPopover({`
    url: $(this).data('url'),
    title: 'Save data',
    type: 'async',
    animation: 'pop',
    backdrop: true,
    closeable: true,
    cache: false
  });
```
thanks
