### ISSUE TITLE
Using webui-popover in a dynamic tablelist

### ISSUE THREAD

**Issue by interwap** [sandywalker/webui-popover#217]
This may not be totally related to the build, but i've be scouring the internet for a solution with no avail. I be glad if the team is able to help me with this.

so i have a table outputting some results to the screen in tabular form. For each table row, i have a column with a icon (more). What i want to achieve is that for each icon, on click its shows a popover, similar to what tidal does but so far, i only get it work just for the last item on the list. 

Here is what i've done so far; please note that the css and js for webui popover have been properly included in the project

My HTML Markup for my rows
    
`<tr><td>'.$name.'</td>`
`<td>'.$title.'</td>`
`<td><a id="'.$id.'" class="more" data-id="'.$id.'" href="javascript:void(0);"><i class="material-icons">more_horiz</i></a></td></tr>`

My js for functionality
`var more = document.getElementsByClassName('more');`

First i'm getting all items with the class more and looping through them

```
for (var i = 0; i < more.length; i++) {

   more[i].onclick = function(){
   var uid = this.dataset.id;

    //Popover
    $('#'+i).webuiPopover({
    url:'#pop-content',
    trigger:'click' ,
    style: 'v2',
    placement:'bottom-left',
    animation:'pop',
    width: '180'});
    }
 }

Html for pop content

```
```
<div id="pop-content">
  <a class="collection-item title">Signed in as</a>
  <div class="divider"></div>
  <a href="#!" class="collection-item">Support</a>
  <div class="divider"></div>
  <a href="#!" class="collection-item">Settings</a>
</div>

``````
Straight out of the box you can see that each row is supposed to show the popover on click of the more icon but its not just doing that. Please feel free to review the documentation and help figure out what i'm not doing correctly. Thanks in advance.

**Comment by sandywalker** [comment]
Sorry for replay so late. 
In your situation, I think it's because the plugin dose not support this feature. 
I suggest you write the code like this
```js
$('.more').webuiPopover({
      trigger:'click',
      style:'v2',
      placement:'bottom-left',
      animation:'pop',
      widh:180,
      content: $('#pop-content').html()
});
```
Do not use url, use content directly.

**Comment by interwap** [comment]
Thanks @sandywalker i already solved it using 

`for (var i = 1; i <= more.length; i++) {

     //Popover
       $('#' + i).webuiPopover({
            content: function(){
             var html = '<div id="pop-content">';
             html += '<div class="divider"></div>';
             html += '<a href="#!" class="collection-item active">Buy</a>';
             html += '</div>';
             return html;
      },
     trigger:'click' ,
     style: 'v2',
     placement:'bottom-left',
     animation:'pop',
     width: '180',
     cache: false
    });

      }`

Thanks all the same.
