### ISSUE TITLE
How to update the options after initializing?

### ISSUE THREAD

**Issue by andrius-senulis** [sandywalker/webui-popover#225]
Hello,

Am I missing something extremely simple or it's not possible to update the options of the popover after initializing it?

Regards,
Andrius

**Comment by Edddy** [comment]
You can use `WebuiPopovers.setDefaultOptions(options);` to change the default options 

Or change the way a new popover behaves using 

```
$('a').webuiPopover({content:'Content',width:300,height:200});
```
