### ISSUE TITLE
Use a class as selector

### ISSUE THREAD

**Issue by dbd5** [sandywalker/webui-popover#226]
Hello,

It seems intuitive to use a class as selector, why can't I use a class as selector like below?
 
        $('.hoverme').webuiPopover({
            trigger:'hover',
            title:'Title',
            content:'Content'
        });

Must I use only the 'a' tag as in the documentation?

```javascript
$('a').webuiPopover(options);
```

**Comment by Edddy** [comment]
Yes, you can use whatever selector you want.

**Comment by dbd5** [comment]
Well it certainly doesn't work that way, you get the following error;

Uncaught Error: Unable to get popover content. Invalid selector specified.
    at WebuiPopover.getContent (jquery.webui-popover.js?v=1484908112:656)
    at WebuiPopover.show (jquery.webui-popover.js?v=1484908112:346)
    at jquery.webui-popover.js?v=1484908112:767

When you change to an anchor selector, it then works

**Comment by Edddy** [comment]
The error it's telling you that have not set up the popover **content** correctly.

**Comment by dbd5** [comment]
HI @Edddy ,

So pray tell, the first post contains exactly how the plugin was initialized. - reproduced below;

$('.hoverme').webuiPopover({
        trigger:'hover',
        title:'Title',
        content:'Content'
    });

What is wrong with this?

**Comment by Edddy** [comment]
There is nothing wrong. See for yourself http://jsbin.com/katizixeto/edit?html,js,output

**Comment by dbd5** [comment]
The code is good but it never worked for me
