### ISSUE TITLE
How to customize the cache?

### ISSUE THREAD

**Issue by kenttanl** [sandywalker/webui-popover#229]
I want to show the user's information in webui-popover, and use asynchronous loading and cache,  But, when the a page have more than one same user at that time , couldn't load only once, So, I want to ask next, that can do that? Thanks and sorry my English

**Comment by Edddy** [comment]
You can customize your cache settings using the tools provided by your programming environment (Rails, Node, .net, etc). Webui-popover only provides a basic caching.

**Comment by kenttanl** [comment]
Thanks you for your answer, And is there a way to load data from the page cache based on the index?

**Comment by Edddy** [comment]
I don't understand exactly what you want. Can you write an example?

**Comment by kenttanl** [comment]
Maybe like this:

```html
<span class='user-card' data-userId="tom">Tom<span>
<span class='user-card' data-userId="tom">Tom<span>

<script>
$(function() {
  var settings = {...};

  $(".user-card").each(function() {
    var userId = $(this).attr("data-userId");
    var remoteSetting = {
       url: "http://api/.../user/" + userId + "?format=json";
       content: function(data) {
         return ... ; // return the result of process the data
      } 
    }
     $(this).webuiPopover('destroy').webuiPopover($.extend({}, settings , remoteSetting));
  })

 })
</script>
```
When I click on different 'Tom', it will load the data twice, but they are the same and should be only loaded once, probably is this meaning, sorry my English, thanks

**Comment by Edddy** [comment]
If you do it this way:

    $('.user-card').each(function () {
        var userId = $(this).attr("data-userId");
        var url = "http://api/.../user/" + userId + "?format=json";
	
        $(this).webuiPopover({
            type:'async',
            url: url,
            cache: true, //it's the default, but we set it any way
            content: function (data) {
                return data;
            }
        });
    });

At least webuiPopover will cache each card (will not call 2 times if you click in the same element), but if you have 2 elements with the same ID, you will need to cache it server side (in the api) or use a complex schema client side to cache the calls (not recommended)

**Comment by kenttanl** [comment]
Yes, That's what I mean, I know how to do it, thank you for your answer
