### ISSUE TITLE
Width is bigger than screen on mobile

### ISSUE THREAD

**Issue by felipedgarcia** [sandywalker/webui-popover#236]
When I'm in a mobile device, popover has invalid width or I may say left css invalid value.

Look:
![popover-error](https://cloud.githubusercontent.com/assets/6040732/26420582/5e8d63b6-4099-11e7-9a88-e05ec2d2c280.png)

If I set the left to 0 in web developer for example it works properly. Looking at the .js the line where this parameter is set is 432. 

How can I solve this? Is there some parameter that I missed?

**Comment by Edddy** [comment]
The content inside the popover surely forced it to go off screen. Please check it

**Comment by felipedgarcia** [comment]
I found what is causing the problemn. The select that can be seen has too long values. So I put a "max-width: 100%" in css and it solves the problemn. It doesn't stay perfect but solves.
