### ISSUE TITLE
how to use destroy or remove popover 

### ISSUE THREAD

**Issue by tks1998** [sandywalker/webui-popover#278]
I try to destroy popover with element id : webuiPopover0  or class :  webui-popover bottom in . I use funtction destroy but it doesn't work . 
![image](https://user-images.githubusercontent.com/37293650/51925588-f554b200-2421-11e9-92f2-739f160b47d8.png)
I try to destroy element with id =webuiPopover0 ; $('#webuiPopover0').webuiPopover('destroy');
but it doesn't work. Please help me :(

**Comment by tks1998** [comment]
I try to destroy popover with element id : webuiPopover0  or class :  webui-popover bottom in . I use funtction destroy but it doesn't work . 
![image](https://user-images.githubusercontent.com/37293650/51925588-f554b200-2421-11e9-92f2-739f160b47d8.png)

**Comment by tks1998** [comment]
I try to destroy element with id =webuiPopover0 ; $('#webuiPopover0').webuiPopover('destroy');
but it doesn't work.

**Comment by Edddy** [comment]
Do you want to hide it? `use $('#webuiPopover0').webuiPopover('hide');`
