### ISSUE TITLE
dismiss webui-popover on clicking page behind doesn't work

### ISSUE THREAD

**Issue by relipse** [sandywalker/webui-popover#36]
I am using async url: and when the popover shows I cannot get it to close by clicking the page behind it. Is this normal or how do I enable this method to close the popover. Thanks

**Comment by Venzon** [comment]
there is no such feature

**Comment by Edddy** [comment]
I've found that it does work the first time but it does work the rest of the time (in the same page). Can you confirm this is happen to you also? 

I think it's a problem binding the events

**Comment by Edddy** [comment]
Was fixed in 1.1.2
