### ISSUE TITLE
When opening an async webui-popover the height gets bigger before loading content a 2nd time

### ISSUE THREAD

**Issue by relipse** [sandywalker/webui-popover#37]
For example, if I click the first time, the ajax will spin until the content is loaded, however if I close the popover and then click a second time, the height will be plus around 50 pixels until it loads async again.

Any ideas?

**Comment by sandywalker** [comment]
Ah, I  will check this problem and fix it

**Comment by sandywalker** [comment]
Sorry, I can't find the problem you described above，will you please paste your code and tell me the web browser which you are using? thanks
