### ISSUE TITLE
Popover not hide if click on body page, after get data in async mode.

### ISSUE THREAD

**Issue by InteLigent** [sandywalker/webui-popover#39]
Check on demo http://sandywalker.github.io/webui-popover/demo/ button "pop async".

Simple solution:
add code
```js
that.bindBodyEvents();
```
after line: https://github.com/sandywalker/webui-popover/blob/master/dist/jquery.webui-popover.js#L301

**Comment by sandywalker** [comment]
Thanks ,the bug is already fixed!
