### ISSUE TITLE
Wail until images are loaded

### ISSUE THREAD

**Issue by crisk** [sandywalker/webui-popover#41]
Hi,

i use webui-popover to show a detailed / bigger image of a product if you hover the product image:
\<img class="img-hover" data-hover="images/big-image.jpg"  src="images/normal-image.jpg"\>

popover is bound to .img-hover:
$('.img-hover').webuiPopover({
			type: 'html',
			content: function(data) {
				return '\<img src="' + $(this).attr('data-hover') + '" /\>';
			},
			placement: 'auto',
			trigger: 'hover',
			constrains: 'vertical',
			delay: 1,
			multi: false,
			arrow: true,
			closeable: false,
			padding: true
		});

it creates a popover and as content it takes the data-hover value which is the path to another image and returns an image tag.
the problem is, that the image is not yet loaded if the popover appears the first time (on hover).
if the image is finaly loaded the popover does not change its position but shows the image and now the popover is so big it flows over the actual normal product image instead of appears above or below.
is there a possibility to wait, till all images (in this case only one image) are loaded and then show the popover (or at least an waiting/loading image).
thank you!

**Comment by sandywalker** [comment]
Sorry, the plugin does not support this situation yet，I'm trying to find some way to implement it.
Maybe you can set width/height with some fixed value,or use css to constrain the image size.
Thanks

**Comment by crisk** [comment]
unfortunately in our case we have a lot of images with different sizes so it's not possible... 
this feature would be great :-)
thanks!

**Comment by crisk** [comment]
Hi! are there any news?
Thank you!

**Comment by NARKOZ** [comment]
Use https://github.com/desandro/imagesloaded
