### ISSUE TITLE
get initiating element from popover element

### ISSUE THREAD

**Issue by Marthoni-Anders** [sandywalker/webui-popover#45]
something like
var triggerElement = $('.webui-popover').getTriggerElement();

So you're able to destroy the element

**Comment by sandywalker** [comment]
If you want to destroy the pop element, you can just call destroy method from the popover object, or you can write code like: $('.webui-popover').webuiPopover('destroy');

**Comment by Marthoni-Anders** [comment]
Hi Sandywalker, I already tried this, I remove the element with $('.webui-popover').hide().remove();

However if I do that I have to click twice on the element that shows the popover element, if there was a data-* to indicate the trigger element I think this could help.

**Comment by sandywalker** [comment]
Oh,I had a little misunderstanding before.
This feature is added to the plugin,now you can  invoke getTriggerElement by the plugin , or you can get trigger element by $('.webui-popover').data('trigger-element') ;
