### ISSUE TITLE
Callbacks

### ISSUE THREAD

**Issue by liammcsheffrey** [sandywalker/webui-popover#49]
Hi, I'm having issues using the callbacks, they don't seem to execute. Is there an issue?

**Comment by sandywalker** [comment]
There is no issue about this , just submit your issues

**Comment by liammcsheffrey** [comment]
Hi, Could you offer an example of a callback in use, such as 'hide'? I didn't see one in the demo.

Many Thanks

**Comment by sandywalker** [comment]
You can write code like: 
```javascript
 $(trigger-element).on('hide',function(e){

});
