### ISSUE TITLE
Clarify minimum jQuery version

### ISSUE THREAD

**Issue by QuentinFchx** [sandywalker/webui-popover#50]
in [bower.json](https://github.com/sandywalker/webui-popover/blob/master/bower.json#L26) it asks for `jquery ^2.0.0`
in the [Readme](https://github.com/sandywalker/webui-popover/blob/master/README.md) is says it works with `jQuery 1.7+   // ie8+`

**Comment by sandywalker** [comment]
Oh, Sorry, That's my fault. I'll fixed it
Thanks
