### ISSUE TITLE
Wrong popover position

### ISSUE THREAD

**Issue by hoangdo94** [sandywalker/webui-popover#52]
Hi.
I've Just found this awesome plugin :)
It works well on provided examples, but when I try to add it to my Wordpress plugin, the Popovers show up in wrong position and I can't find out why.
Can you check it?
Thanks

**Comment by sandywalker** [comment]
May be the problem is css position conflict with the Wordpress,  I'm not sure. Can you paste some of the code or screenshots for more info?

**Comment by hoangdo94** [comment]
I've found the problem, thanks.

**Comment by alexfilatov** [comment]
@hoangdo94 having the same issue, could you please share what solved this issue for you?
thanks!
