### ISSUE TITLE
is it possible to initialize pop and show in one click

### ISSUE THREAD

**Issue by inshaf** [sandywalker/webui-popover#53]
hi

thanks for wonderful plugin :+1:  i wanted to initiate the popup when user click on a button and show the popup right away. Simply, in one click, initialize and show. 

Could u pls give me some sample code as well

thanks :)

**Comment by jaredreich** [comment]
+1 for this

**Comment by sandywalker** [comment]
Here's my sample code
```javascript
$('#someButton').on('click',function(e){
    e.preventDefault();
    var popover = $(this).data('plugin_webuiPopover');
    if (popover){
        popover.toggle();
    }else{
       $(this).webuiPopover({options...}).webuiPopover('show');   
    }
});
```
Hope I did not misunderstand what you mean.

**Comment by inshaf** [comment]
thanks alot and it is working :+1:
