### ISSUE TITLE
Drag and maxmization features requirement

### ISSUE THREAD

**Issue by limodou** [sandywalker/webui-popover#54]
What about adding drag and maximization support to webui-popover?

For maximization, the options could be:

maxWidth: 'none' // 'none' is default means can't be maximized, 
                            // 'auto' means maximize to full document width
                            // 'n%' means enlarge to n percent of full document width
maxHeight: //just like above

if one of maxWidth and maxHeight is not 'none', it'll place a maximization icon int the right-top cornor of the popup dialog.

**Comment by sandywalker** [comment]
I'll think about it and check if the plugin can still lightweight with this feature . 
Thanks for your advice!
