### ISSUE TITLE
Programmatically open and close popover

### ISSUE THREAD

**Issue by jaredreich** [sandywalker/webui-popover#56]
After creating the popover:
```
$('#element-id').webuiPopover({
    title: 'Title',
    content: 'Content'
});
```

Functions like this would be excellent:
```
$('#element-id').webuiPopoverShow();

$('#element-id').webuiPopoverHide();
```

**Comment by sandywalker** [comment]
You can open or close popover like this
```javascript
$('#element-id').webuiPopover('show');
$('#element-id').webuiPopover('hide');

**Comment by nevkatz** [comment]
Thank you! On my end, it looks like the popover closes after the click event terminates. This seems to also be the case for when other events terminate, such as mouseover or hover. Is there a way to make the popover stay open after the click has ceased?
