### ISSUE TITLE
Animation for close

### ISSUE THREAD

**Issue by jaredreich** [sandywalker/webui-popover#57]
Would be nice to have the chosen animation take place for when the popover closes as well.

**Comment by sandywalker** [comment]
Yes, this feature can be done in near feature.
Thanks.

**Comment by lenamtl** [comment]
+1

**Comment by KrishnaPG** [comment]
+1 Looking for a way to use "JQuery Transfer effect" to make it look like it moved into some other element (such as notification center) upon dismissal.

**Comment by sandywalker** [comment]
The close animation is already implemented . Sorry for so long postponed.
