### ISSUE TITLE
twice click  then show

### ISSUE THREAD

**Issue by byends** [sandywalker/webui-popover#59]
code like this:
```
$('.test').on('click', function() {
  $(this).webuiPopover({
     content: 'hello world'
  });
});
```

it need twice click then show, why ?

**Comment by sandywalker** [comment]
The plugin will handle the click event itself when the trigger option is set to 'click', so you don't need to write click event handler. just write like this:
```javascript
$('.test').webuiPopover({
     content: 'hello world'
  });

**Comment by byends** [comment]
sometimes, i want to do something before webuiPopover response.

**Comment by byends** [comment]
@sandywalker  Don't you think it's a design problem?

**Comment by BlackImpl** [comment]
+1

**Comment by BlackImpl** [comment]
@byends  Did you find solutions?

**Comment by justinhomes** [comment]
i have this same problem having to click twice
