### ISSUE TITLE
mouse relative placement option

### ISSUE THREAD

**Issue by ezraroi** [sandywalker/webui-popover#61]
currently all placements options are fixed positions. 
Another good place to display the popover can be relative to the current mouse location

**Comment by Edddy** [comment]
I think it's outside the scope of this project. There are plenty of other plugins that do it. For example QTip 2 http://stackoverflow.com/questions/9608990/how-to-make-a-qtip-tooltip-move-with-cursor

**Comment by vanboom** [comment]
:+1:  When clicking on objects that have some off-screen sizing, the popover should render at the mouse position instead of somewhere else on the element.
