### ISSUE TITLE
how to attach webuiPopover to dynamic content?

### ISSUE THREAD

**Issue by zozzi** [sandywalker/webui-popover#62]
hello,
please, how to attach webuiPopover to dynamic content load by ajax?
P.

**Comment by woohling** [comment]
Same problem here

**Comment by sandywalker** [comment]
The plugin can not support this feature now,I'll try to solve the problem. 
 If you have any good suggestions, please leave comments.
Thanks.

**Comment by crisk** [comment]
@woohling 
try datatable event page.dt  
$('#example').on( 'page.dt', function () {
 // reinit webui
});

**Comment by kalburgimanjunath** [comment]
popovere is opening on 2nd click

**Comment by leonardostefani** [comment]
This small hack works for me :+1: 

``` javascript
$('#myInput').on('focus',function(){
   $(this).webuiPopover('destroy');
   $(this).webuiPopover({
      placement: 'right',
      content: function(){ return Date.now }
   }); 
});
```

**Comment by kalburgimanjunath** [comment]
Please use Following code works for me.

$('#myInput').on('focus',function(){
   $(this.parentElement).webuiPopover('destroy'); // the trick
   $(this.parentElement).webuiPopover({
      placement: 'right',
      content: function(){ return Date.now }
   }); 
});
