### ISSUE TITLE
Do not hide while focus is there

### ISSUE THREAD

**Issue by chang-zhao** [sandywalker/webui-popover#66]
If triggered by hover, a popover hides even when there is a focus on input field in it.

Please could it be modified so that a mouse leave doesn't hide a popover while some child element has focus?

Otherwise it causes glitch, e.g. when a dropdown selection of suggestions for the input text field gets over the border of a popover so it closes on losing hover; so a dropdown selection closes unexpectedly; and later on it has wrong height.

**Comment by sandywalker** [comment]
I suggest you use  trigger: 'manual' instead, then you can handle the events your self
