### ISSUE TITLE
Little fix cause of the xhr.abort issue

### ISSUE THREAD

**Issue by crisk** [sandywalker/webui-popover#67]
Hi @sandywalker 
i just noticed that if you quickly mouse over a popover (mouseenter & mouseleave)  in async mode and cache enabled it aborts the xhr (which is good) but if you want to trigger the popover again (e.g. on mouseenter) your plugin thinks the content is already in cache, but it issnt (because hxr was canceled) and never tries to make the ajax call again.
i just added
this._poped = false in line 104:
if (this.xhr){
						this.xhr.abort();
						this.xhr = null;
						this._poped = false;
					}

and now it works fine!

**Comment by crisk** [comment]
oh no... i think a made a mistake...
this is not the solution.
now i just added:
if (!this.getCache() || !this._poped || this.content === ''){ ...
this works much better!

**Comment by sandywalker** [comment]
Sorry for reply so late, your suggestion is great!
Thanks !

**Comment by rahilwazir** [comment]
Have you implemented this to source yet?

**Comment by sandywalker** [comment]
This issue is fixed
