### ISSUE TITLE
Use with an imagemap

### ISSUE THREAD

**Issue by verdonv** [sandywalker/webui-popover#75]
Hi,

Any suggestions or thoughts on how to position the popover with an image map? I have tried a variety of settings, and I guess it's using the canvas as point of reference for placement, as the popover triggers are with the map, and not on the canvas so to speak.

![screen shot 2015-05-19 at 9 36 45 am](https://cloud.githubusercontent.com/assets/5149763/7704261/3b0d8dc6-fe0b-11e4-8cea-4f0024fe22d4.png)

**Comment by verdonv** [comment]
I did find another way to make this work... essentially creating a fixed size div and using the image as a background-image in that, then defining the hot spots within that div with fixed positioning. It's a lot of markup, but does work well.

**Comment by sandywalker** [comment]
Sorry, the plugin's position is based on Dom,not canvas. 
I can't find any good way to fix this either.
