### ISSUE TITLE
Use with other scripts required for rendering content

### ISSUE THREAD

**Issue by verdonv** [sandywalker/webui-popover#76]
Hi,

I realize this isn't an issue/bug with webui-popover. I'm not sure where else to have a conversation about a specific usage, perhaps a little out of the norm.

In the use case I am working on, the content in my pop-ups will have a lot of math functions and formula, which require rendering with MathJax. The issue I've discovered is that when the pop-up content is rendered in the pop-up, MathJax is not triggered again. I actually found a conversation about this very same issue, in the context of Moodle and whatever mechanism it uses for pop-ups...

> This is not a problem with MathJax being loaded, but instead a synchronization issue. The popup loads its content with your mathematics when the link is clicked. This is normally after MathJax has already typeset the whole page. It needs to be told to reprocess it once again after the popup has loaded.

> I was able to get it to work by editing moodle/filter/glossary/yui/build/moodle-filter_glossary-autolinker/moodle-filter_glossary-autolinker.js  and adding the statement

> MathJax.Hub.Queue(['Typeset',MathJax.Hub]);

> before the line

> return true;

I'm guessing I can do something like this within query.webui-popover.js but am not quite sure where to start. The show:function maybe or the displayContent:function perhaps?

Any suggestions would be quite appreciated. 
v

**Comment by sandywalker** [comment]
Can you send me some demo code?
I can test the code  and try to solve the problem.

**Comment by verdonv** [comment]
Hi Sandy,

Thanks for following up. A person on the MathJax discussion group offered a solution late Friday, which worked quite well

> The WebUI Popover triggers a custom event when the popover has been displayed, so you can use that to trigger MathJax to typeset the contents of the popover.  In your case, you can use
>
>	$('a.show-pop-1').on("shown.webui.popover",function () {
>	  MathJax.Hub.Queue(["Typeset",MathJax.Hub,this.getAttribute("data-target")]);
>	});
>
> to make the binding.  This can go in your initPopover() function.

There is a slight flicker (if you're watching close) when the popover content re-renders, but it's hardly noticeable.

**Comment by verdonv** [comment]
The example is here at the moment..

https://verdonv.nipissingu.ca/mj/
