### ISSUE TITLE
exports WebuiPopover to window?

### ISSUE THREAD

**Issue by todaylover** [sandywalker/webui-popover#77]
I try to pop React Component by this plugin, so I follow [this advise](http://stackoverflow.com/questions/20033522/rendering-a-react-component-inside-a-bootstrap-popover).
that need override WebuiPopover's setContent method. I expect exporting WebuiPopover to window.

Or call the content function with WebuiPopover instance object parameter which I can update the content  manually with , then ignore the return value(undefined?).

now I use ` $.data(this,'plugin_webuiPopover')` to get WebuiPopover instance object
```
  $('.account-user').webuiPopover({
        content:function(data){
            var popover = $.data(this,'plugin_webuiPopover');
            var contentElement = popover.getContentElement();
            if (data.data) {
                var ele = React.createElement(UserCard,{user:data.data});
                React.render(ele,contentElement[0]);
                return undefined;
            }
       }
});
```

**Comment by sandywalker** [comment]
Thanks for your advice.
I'm not very familiar with the React and don't really know how to optimize  the plugin to work well with React.
But I'll learn React recently and find way to solve the problem.

**Comment by sandywalker** [comment]
I'm writing the version 2 of this plugin with es6, this problem will be fix in the new version.
