### ISSUE TITLE
Please correct the placement near screen borders

### ISSUE THREAD

**Issue by chang-zhao** [sandywalker/webui-popover#78]
When a popover target is near screen border, the popover can get partly off-screen with no simple way to see that part. Please make a correction when calculating the placement coords.
For example:
    left: pos.left + pos.width / 2 - targetWidth / 2
should be
    left: Math.max(0,pos.left + pos.width / 2 - targetWidth / 2)
etc.

**Comment by sandywalker** [comment]
Thanks for your advice. 
But your solution will cause some other problem when I tried.
I'm too busy these days, the plugin will be update when I find a better way.

**Comment by sandywalker** [comment]
You can try 'auto-bottom' option, hope this will solve your problem.

**Comment by chang-zhao** [comment]
As I said, the placement algorythm was wrong regardless of options. And how could my solution cause other problem? When a negative offset would be needed???

**Comment by sandywalker** [comment]
You are right, I've fixed this problem.
