### ISSUE TITLE
Cannot override template

### ISSUE THREAD

**Issue by gholol** [sandywalker/webui-popover#80]
So i want to change popover template

    var template = '<div class="customclass">'+
    '<div class="arrow"></div>'+
    '<div class="webui-popover-inner">'+
    '<h3 class="webui-popover-title"></h3>'+
    '<div class="webui-popover-content"><i class="icon-refresh"></i> <p>&nbsp;</p></div>'+
    '</div>'+
    '</div>'

    $('.blob a').webuiPopover({
        template: template,
        trigger: 'hover',
        type: 'async',
        url: '/ajax/getuser.php?id=3',
        cache: false,
        content: 'Example content, nothing to see here',
        placement: 'right'
    });

But it doesn't changes, no matter what I do, modal still contains original HTML code. Is this parameter working?

**Comment by sandywalker** [comment]
Sorry, my problem. 
This parameter is working however with some bugs, the customClass is replaced by pluginClass when plugin showing.
I'll fixed this.

**Comment by gholol** [comment]
Okay, thanks alot!
