### ISSUE TITLE
can reset position popover after open modal ?

### ISSUE THREAD

**Issue by OPGamesTH** [sandywalker/webui-popover#81]
Video https://drive.google.com/file/d/0BzBdI6OVibQULXlpY3VaTXNzS2c/preview

sorry my bad english

//Javascript
$('[data-loadajax="popover"]').on('mouseover', function(){
	var URL = $(this).attr("data-loadurl");
	var Target = $(this).attr("data-target");
	var profile_loading = {
		trigger:'hover',
		placement:'auto',
		content:'<iframe src="' + URL + '" style="width:100%;height:202px;overflow:hidden;" frameborder="0" scrolling="no"></iframe>',
		width:350,
		cache:false,
		multi:false,
		closeable:false,
		style:'',
		padding:true,
		arrow:false
	};
	$(Target).webuiPopover(profile_loading);
});
//id i use function random text
< a id="profile-wqe6asd" data-loadajax="popover" data-loadurl="popover.php?profile=test" data-target="#profile-wqe6asd" class="link_hover">Example</a>

**Comment by sandywalker** [comment]
Sorry,My network is not very stable, so I can't view the video you posted. 
Would mind upload the video to youtube and send me the url?

**Comment by OPGamesTH** [comment]
https://www.youtube.com/watch?v=IQIfj2jbP6A

**Comment by sandywalker** [comment]
I saw the video , the plugin did recalculate the position of the popover every times.
Maybe you can disable cache by set  cache:false, and try again.
