### ISSUE TITLE
Popver is closing after click on autocomplete

### ISSUE THREAD

**Issue by faralimite** [sandywalker/webui-popover#83]
Hello,

I created a popover with an input using autocomplete to filter the results. My issue is when I'm clicking to selected value from autocomplete the Webui popover is closing.

Can anyone help me to fix this thing?

Regards,
Radu

**Comment by sandywalker** [comment]
The reason is because the plugin handle the click event on body,I will add a option to control  whether handle this event,please wait!

**Comment by faralimite** [comment]
I'm looking forward for it. :+1:

**Comment by faralimite** [comment]
hello, any news for this fix?

**Comment by sandywalker** [comment]
New option 'dismissible' is added to the plugin, default value is true. you can turn it to false, so that the popover will not handle document body event.
Please go and try it.

**Comment by faralimite** [comment]
is there any option to use 'dismissible' just for inside content? I want when I use autocomplete to be able to select the result but when I will click on body, to hide it. thanks.

**Comment by sandywalker** [comment]
It seems contradiction,you may handle body click event your self.

**Comment by faralimite** [comment]
Hi. If I'm open a popover with dismissible true, close it, and open other popover with dismissible false the popover with dismissible true is going to be with dismissible false.

**Comment by faralimite** [comment]
hello, any news for this fix?

**Comment by sandywalker** [comment]
In this situation, I suggest that you set the cache option to false, and the problem should be fixed!
