### ISSUE TITLE
trigger hover stops another click action

### ISSUE THREAD

**Issue by quasiperfect** [sandywalker/webui-popover#88]
hi 

thanks for your work

i have a problem implementing your script

on a link on hover i want to show a popover and on click to do something else
your plugin disables my other action for some reason (the click action works if i disable the plugin)
any ideea how i could solve that ?

**Comment by sandywalker** [comment]
I tested this situation , but could't find the problems, everything works ok.
Here's my code
```javascript
$('#popover_test2').webuiPopover({
                trigger:'hover',
                content: 'content<br>dddd<br>dddd<br>dsfsdfsdf<br>dddd<br>dddd<br>dsfsdfsdf'
        });

        $('#popover_test2').on('click',function(e){
            e.preventDefault();
            alert(1);
        });
```

**Comment by quasiperfect** [comment]
thanks for responding

here is how i try to use it

http://jsfiddle.net/4uy9a67j/

**Comment by quasiperfect** [comment]
@sandywalker  can you please try the jsfiddle

**Comment by sandywalker** [comment]
@quasiperfect  I tried the jsfiddle and finally found the bug and fixed it.
Thanks for your comment!

**Comment by quasiperfect** [comment]
@sandywalker thank you for your work
