### ISSUE TITLE
Async-Popovers don't close anymore

### ISSUE THREAD

**Issue by ghandmann** [sandywalker/webui-popover#91]
Hi There,
i just recognized that with the latest version async popovers can't be closed anymore.

I've just bisect'ed the issue and found the first bad commit: 97f271ca50eb7b62694ab0c84b681337b7dded2e

The parent (9f16e61) is working fine.

Sadly there aren't any errors reported in the JS-Console (neither Opera, Chrome, Firefox).

**Comment by ghandmann** [comment]
Just recognized, that there is already a **working** Pull-Request on this Issue!
See #89

**Comment by SaurabhKapoor123** [comment]
Please help Me
Async-Popovers not close after on mouse leave

**Comment by longxinH** [comment]
How to deal with

**Comment by longxinH** [comment]
How to deal with
Async-Popovers not close after on mouse leave

**Comment by Minishlink** [comment]
Anyone else still has the problem ? I'm on 1.1.6 and it does happen.
