### ISSUE TITLE
elements in Popover not available for focus

### ISSUE THREAD

**Issue by vnaag** [sandywalker/webui-popover#93]
Hi ,
I have been tryin to set focus on an input field when the pop up is loaded(Shown) event.
However I'm unable to set focus on the input field.
I have tried inducing a delay as well.
Nothing seems to work
Please help.

**Comment by sandywalker** [comment]
You must handle  'shown.webui.popover' event ,not 'shown' event.
Here is sample code:
```javascript
$el.webuiPopover({
            content:'<form action=""><input type="text" id="in" /></form>'
        }).on('shown.webui.popover',function(){
           $('#in').focus();
        });
```
