### ISSUE TITLE
Pop up Doesnt open on second click

### ISSUE THREAD

**Issue by vnaag** [sandywalker/webui-popover#94]
Hi,
I'm using the popover on a link click. The popover contains a button, on click of which an iframe is loaded.
When user navigates to the original page and clicks on the link to open the pop over window, the pop over window doesnt appaear.
I checked the developer tools in Chrome and see that "display : none" is set on the pop over.

please suggest on the same

**Comment by Edddy** [comment]
Try using `cache:false`
