### ISSUE TITLE
Umm... okay. So how do I access data attributes inside webuiPopover?

### ISSUE THREAD

**Issue by gholol** [sandywalker/webui-popover#97]
$('#something').find('a[data-toggle="popover"]').webuiPopover({
            trigger: 'hover',
            type: 'async',
            async: {
                success: function (that, urlResult) {

                    //How to access data attributes?? this one returns undefined
                   console.log($(this).data('author'));

                    $.get('/tpl/sometemplate.mst').done(function (templateData) {

                        Mustache.parse(templateData);
                        var html = Mustache.render(templateData, urlResult.content);

                         //ugly workaround as there's no other way to do it...
                        that.setContent(html);
                    });
                }
            },
            html: true
        });

**Comment by sandywalker** [comment]
You can access data attributes by using 'that' parameter in callback function,  for example
```javascript
that.$element.data('author');
```

**Comment by gholol** [comment]
Thanks! it worked
