### ISSUE TITLE
How two elements bound to the same pop-up box

### ISSUE THREAD

**Issue by longxinH** [sandywalker/webui-popover#99]
I would like to bind two different elements with a pop-up box

**Comment by sandywalker** [comment]
You can just use class selector to trigger multi elements, like $('.my-trigger').webuiPopover({...}) .

**Comment by longxinH** [comment]
What I mean is a class public id webui-popover0
![tmp40b529e3](https://cloud.githubusercontent.com/assets/12230340/9153623/0077d920-3e96-11e5-9662-df7aebe387b7.png)

**Comment by sandywalker** [comment]
Oh, the plugin does not support this feature.
